### ISSUE TITLE
XData Block error when compiled

### ISSUE THREAD

**Issue by rodoctor** [intersystems-community/vscode-objectscript#1128] opened 2023-04-04 11:25 UTC
When creating an XData block with the mimetype application/json, an error occurs when compiling.
The same class compiled in Studio works perfectly.

Example:

```objectscript
Class tests.mock.base.TestXData Extends %RegisteredObject
{
    XData example [ MimeType = application/json ]
    {
        {
            "return": true
        }
    }
}
```

**Comment by isc-bsaviano** [comment] 2023-04-04 11:50
@rodoctor That class compiles fine for me. Can you as screenshot or copy/paste the error that you're seeing?

**Comment by isc-bsaviano** [comment] 2023-04-04 12:36
@rodoctor What is the `$ZV` of your IRIS instance, and what version of this extension are you using?

**Comment by rodoctor** [comment] 2023-04-04 12:43
> @rodoctor What is the `$ZV` of your IRIS instance, and what version of this extension are you using?

w $ZV
Cache for UNIX (Red Hat Enterprise Linux for x86-64) 2017.2.1 (Build 801U) Wed Dec 6 2017 09:23:15 EST

vscode-objectscript - v2.6.0

**Comment by isc-bsaviano** [comment] 2023-04-04 13:27
@rodoctor That's a very old version. I couldn't get it to install on my Windows machine, but I was able to install a newer Cache kit with a `$ZV` of `Cache for Windows (x86-64) 2018.1.8 (Build 766U) Wed Mar 8 2023 21:42:22 EST`. I couldn't reproduce your issue with that kit. Since this works with IRIS and newer Cache kits, I don't think there's a bug in this extension. I suggest you upgrade if possible.

**Comment by isc-bsaviano** [comment] 2023-04-04 20:27
@rodoctor I confirmed that the server-side fix for this issue is in Cache/Ensembe versions 2018.1.0 and above. You should be able to compile the class if you remove the `MimeType = application/json`. This bug will only occur for the `application/json` MimeType.

**Closed by isc-bsaviano** 2023-04-04 20:27 UTC

**Comment by rodoctor** [comment] 2023-04-05 00:47
Thank you very much for identifying the problem. The extension is excellent.
