### ISSUE TITLE
troubles with DB connection

### ISSUE THREAD

**Issue by xoxloviwan** [intersystems-community/vscode-objectscript#440] opened 2020-10-26 10:36 UTC
Version 1.0.3 is not able to connect to DB (I don't use InterSystems Server Manager, it was yet too raw). I try to connect with this params:

    {
      "objectscript.conn": {
        "host": "localhost",
        "port": 57772,
        "username": "dev0",
        "ns": "LOCAL",
        "https": false,
        "active": true
      },
      "objectscript.export": {
        "folder": "\\Code\\",
        "atelier": false,
        "generated": false,
        "filter": "",
        "category": {},
        "noStorage": false,
        "dontExportIfNoChanges": false,
        "maxConcurrentConnections": 0
      },
      "objectscript.suppressCompileMessages": false,
      "objectscript.serverSideEditing": false,
      "objectscript.debug.debugThisMethod": false,
      "objectscript.format": {
        "commandCase": "lower",
        "functionCase": "lower"
      }
    }
when I input correct password it does't show anywhere. Only symbol of cross.
In version 1.0.1 it writes Connected or ERROR. Besides, application try to connect too much times. Cache has connection limit, and it not allow connect after some attempts. Now I downgrade to 1.0.1.

**Comment by daimor** [comment] 2020-10-26 10:38
Anything, when you hover the text on status bar?

**Comment by xoxloviwan** [comment] 2020-10-26 11:41
ERROR - Not Authorized.
After input correct password in command palette, prompt reopen again.

**Comment by gjsjohnmurray** [comment] 2020-10-26 14:49
Please try the latest beta from https://github.com/intersystems-community/vscode-objectscript/releases

**Comment by gjsjohnmurray** [comment] 2020-10-26 18:13
> I don't use InterSystems Server Manager, it was yet too raw

@xoxloviwan please log issues at https://github.com/intersystems-community/intersystems-servermanager/issues so we know how to turn it from "too raw" to "just right".

**Comment by xoxloviwan** [comment] 2020-10-28 13:16
I don't understand what minimal set of packages will correct work with DB. When I try to start work with vscode-objectscript extention some months ago, it was one minimalistic extention. Now it recommended me obsessively install extention InterSystems Language Server and InterSystems Server Manager.

I install version v1.0.4-beta.6 InterSystems ObjectScript and InterSystems Language Server v1.0.3. And the problem is not solved.
I don't understand what from this extentions interrupts other and where from repos Issues I need to write.

**Comment by gjsjohnmurray** [comment] 2020-10-28 15:17
@xoxloviwan [here on Developer Community](https://community.intersystems.com/post/using-intersystems-objectscript-vs-code-how-report-issues) there's some new guidance about how the 3 extensions interoperate and which repo to target issues at.

You **can** operate with just one of the three (vscode-objectscript).

By adding Server Manager it becomes easy to consolidate server definitions and possible to store passwords in your local keychain.

And by adding Language Server you get the same quality of code coloring as in Studio, as well as increasingly smart Intellisense-type features.

If the connection issue you reported is that it **never** connects, then this repo is the right place for the issue.

Does the JSON you posted come from the .vscode/settings.json file in your local workspace folder?

You also wrote about it making too many connections and reaching a limit. Do you mean account lockout caused by too many failed authentication attempts?

**Comment by xoxloviwan** [comment] 2020-10-28 20:42
> Does the JSON you posted come from the .vscode/settings.json file in your local workspace folder?

Yes, JSON in [comment](#issue-729447861) from /localfolder/.vscode/settings.json

> Do you mean account lockout caused by too many failed authentication attempts?

Yes

Note that it was so without Server Manager.

Today I read new docs at https://intersystems-community.github.io/vscode-objectscript/ and install all 3 extentions and it situation was not repeat.

I can try to disable Server Manager and Language Manager and try to connect the old way again to check that problem reproduced.

**Comment by gjsjohnmurray** [comment] 2020-10-29 00:10
@xoxloviwan I am glad to hear you are now using all three extensions and you no longer have the problem. What does the `objectscript.conn` object in your .vscode/settings.json file look like now? I guess it uses the `server` property instead of `host`, `port` etc.

There's no need for you to spend time reverting to your old setup and trying to recreate the login problem, unless you particularly want to. But answers to a few more questions may give us some clues about what went wrong before.

> Yes, JSON in [comment](#issue-729447861) from /localfolder/.vscode/settings.json

Was the folder name actually localfolder, or something else?

When you were getting this problem (authentication failure) did you perhaps already have an `intersystems.servers` object defined in your user-level settings.json from a previous attempt to use Server Manager? If yes, did the name of one of your entries match the name of your local folder?

**Comment by gjsjohnmurray** [comment] 2020-10-30 23:17
Likely duplicate of #458

**Comment by isc-rsingh** [comment] 2020-11-06 16:01
This was fixed in 1.0.5

**Closed by isc-rsingh** 2020-11-06 16:01 UTC
Labels: review
