### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Patresko** [intersystems-community/vscode-objectscript#1447] opened 2024-10-08 09:54 UTC
Im getting searching errors when Im trying to search. This error show up for me in certain update of some vscode plugins but not sure which version. 

`TypeError: Cannot read properties of undefined (reading 'folder')`

**Comment by isc-bsaviano** [comment] 2024-10-08 11:05
Duplicate of https://github.com/intersystems-community/vscode-objectscript/issues/1427

**Closed by isc-bsaviano** 2024-10-08 11:05 UTC
