### ISSUE TITLE
New folder vanishes on creation when using filter with isfs folder

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems-community/vscode-objectscript#809] opened 2021-12-17 12:58 UTC
When trying to create a new folder with an isfs folder such as the configuration below, the folder immediately vanishes preventing me from creating classes inside it:
```
{
	"name": "wip22v1:HSLIB",
	"uri": "isfs://wip22v1:hslib/?filter=%ZHS*.inc,*.cls,*.MODULE,*.LOC"
}
```

If I try to create a new folder without the filter applied, it works just fine.
Here is a screen recording of the behavior:

https://user-images.githubusercontent.com/75783557/146547784-ecd75d65-250a-4fbd-81fa-113dbb7ff3ed.mov

**VSCode version:**
Version: 1.63.1
Commit: fe719cd3e5825bf14e14182fddeb88ee8daf044f
Date: 2021-12-14T02:13:13.580Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Extension version:** 1.2.2

**Comment by isc-bsaviano** [comment] 2021-12-17 13:28
@gjsjohnmurray My guess is that the explorer tree is refreshing itself, which is causing the folder to disappear since it doesn't have any contents. Does the presence of `filter` cause the folder to refresh more often?

**Comment by gjsjohnmurray** [comment] 2021-12-17 14:56
> Does the presence of `filter` cause the folder to refresh more often?

@isc-bsaviano I'd be surprised if the presence of a queryparam on the uri causes VS Code's Explorer to refresh from the FSP more frequently. A possible test would be to omit the filter= but add a nosuchparam=1 instead and see if the problem still occurs.

**Comment by isc-bsaviano** [comment] 2021-12-17 15:07
I do see the same behavior with `?nosuchparam=1`. I'll try this using the MemFS sample extension and if I can reproduce the behavior there I'll open a VS Code issue

**Comment by isc-bsaviano** [comment] 2021-12-17 15:36
I was not able to reproduce this using MemFS

**Comment by isc-bsaviano** [comment] 2022-04-11 12:28
@isc-kiyer This will be fixed in VS Code 1.67

**Closed by isc-bsaviano** 2022-04-11 12:28 UTC
Labels: upstream

**Comment by isc-kiyer** [comment] 2022-05-10 14:19
@isc-bsaviano I still see this issue with vs code 1.67. Version info:
Version: 1.67.0 (Universal)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:14:47.100Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

**Comment by isc-bsaviano** [comment] 2022-05-10 14:23
@isc-kiyer Can you comment on the VS Code issue with a screen cap of the bug still existing?
