### ISSUE TITLE
cannot debug objectscript code

### ISSUE THREAD

**Issue by ltjand** [intersystems-community/vscode-objectscript#891] opened 2022-03-02 17:46 UTC
Issue Type: <b>Bug</b>

getting error "debugger can not start".  steps:
1. connect to remote server
2. create launch.json/ or click debug this method on the class method (neither work)
3. Utils.cls is the active window
4. run debug from launch settings selection or click debug this method on the class method.
Here's the launch.json:
{    "version": "0.2.0",
    "configurations": [
      {
            "type": "objectscript",
            "request": "launch",
            "name": "GetNamespaceFromApp",
            "program": "##class(XX.OAuth2.Utils).GetNamespaceFromApp()"
        }
    ]
}

Extension version: 1.4.3
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isc-bsaviano** [comment] 2022-03-02 18:16
@ltjand Does your web server allow for websockets? Usually the "Debugger can not start" error is caused by the inability to upgrade the initial HTTP debugging request to a websocket.

**Comment by ltjand** [comment] 2022-03-02 21:35
I am not sure.  How does one go about finding out?

**Comment by ltjand** [comment] 2022-03-03 20:24
yes, we are using https. I checked the iis server, and it doesn't show we have websocket turned on.  Do we need to turn this on?  Is that all we need to do, and any concerns with leaving it on?

**Comment by isc-bsaviano** [comment] 2022-03-03 20:50
@ltjand If you want to use our debugger then you need to allow websocket connections. Leaving it on won't affect anything else with our extensions and debugging is the only feature that requires websockets.

**Comment by isc-bsaviano** [comment] 2022-04-04 18:04
@ltjand Did debugging work for you after you enabled WebSockets in your web server?

**Comment by ltjand** [comment] 2022-04-04 20:37
I wasn’t able to try it out, because there are concerns about setting this on from the team since they aren’t familiar with this setting and if there would be any adverse effect.

Thanks for following up.

Lena

**Comment by isc-bsaviano** [comment] 2022-04-04 20:40
@ltjand Ok, I'm going to close this issue and if you're experiencing issues after allowing WebSockets please follow up here and I will reopen it.

**Closed by isc-bsaviano** 2022-04-04 20:40 UTC

**Comment by ltjand** [comment] 2022-04-04 20:41
Ok, thanks.
