### ISSUE TITLE
Unable to copy/paste into CSP extension pages on Mac

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems-community/vscode-objectscript#687] opened 2021-06-14 19:23 UTC
The copy and paste commands don't work in inputs on a Studio extension that is a CSP page loaded within VS Code. This only occurs on Mac.

VS Code ObjectScript extension version: 1.0.12
VS Code version: 1.52.2

**Comment by gjsjohnmurray** [comment] 2021-06-14 20:36
VS Code 1.52.2 is getting a bit old. Current release is 1.57. Can you update and retest?

**Comment by isc-pbarton** [comment] 2021-06-14 20:46
Hi John, the user updated to the latest version and is experiencing the same error.

Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

**Comment by gjsjohnmurray** [comment] 2021-06-16 16:50
@isc-pbarton please create a minimal repro and upload here whatever needs to be installed on the server. Bonus points for a short MP4 or animated GIF that illustrates (hint - `Developer: Toggle Screencast Mode` command before recording to reveal your keystrokes)

The underlying issue may be a VS Code one, especially since you only see it when running VS Code on macOS.

**Comment by gjsjohnmurray** [comment] 2021-06-18 10:07
Thanks for the detailed steps which meant I was able to reproduce the problem. Like you said, it happens on macOS but not on Windows. I didn't test on Linux VS Code. I think it's probably related to how the CSP template page gets run in an iframe within a VS Code [Webview](https://code.visualstudio.com/api/extension-guides/webview), which itself  places its contents in an iframe.

Do you know if this problem has always existed? Or did it appear after a recent VS Code update?

**Comment by isc-bsaviano** [comment] 2022-04-21 19:57
@gjsjohnmurray I verified that this is still a bug. Would a possible solution be to use the VS Code simple browser instead of an iframe in a Webview?

**Comment by gjsjohnmurray** [comment] 2022-04-22 12:00
@isc-bsaviano if you use this button in Server manager to launch Portal in Simple Browser, can you paste?

![image](https://user-images.githubusercontent.com/6726799/164710273-7d28be63-dace-44af-aedc-90f7da022d82.png)

**Comment by isc-bsaviano** [comment] 2022-04-22 12:08
@gjsjohnmurray The simple browser isn't working for me at all. It takes forever to load, then when I see the SMP login page I can't paste into either input box and clicking "login" has no effect. I am using a new IRIS so it's possible that there's some server-side setting that I need to change that I'm forgetting.

**Comment by isc-bsaviano** [comment] 2022-04-22 14:00
@gjsjohnmurray I still can't copy-paste into a simple browser.

**Comment by isc-bsaviano** [comment] 2023-10-24 15:00
I have verified that this is still not working, but since there's nothing for us to do in this extension I'm going to close the issue. I will open one on the VS Code repository shortly

**Closed by isc-bsaviano** 2023-10-24 15:00 UTC

**Comment by isc-bspead** [comment] 2025-03-24 20:41
@isc-bsaviano  - I may have missed it, but is there an open VSCode bug that we can point customers to?  We hit this with a Partner today

**Comment by isc-bsaviano** [comment] 2025-03-24 20:44
https://github.com/microsoft/vscode/issues/129178
