### ISSUE TITLE
Source Control does not report an error when write file fails

### ISSUE THREAD

**Issue by marykerins** [intersystems-community/vscode-objectscript#515] opened 2020-11-13 14:55 UTC
I set up source control but the client view in my perforce workspace was not correct.    

I created a new folder and file, added file to source control, and saved.  Output panel message indicated the save was successful.  The new folder was created in the directory tree, but no file.  I repeated the steps using Studio.  After selecting to add file to source control, Studio provided a popup which identified the error:  
" ERROR #5001: Error: /home/mkerins/perforce/SourceControl/cls/CCC/MyClass.xml - file(s) not in client view."

**Comment by gjsjohnmurray** [comment] 2020-11-13 16:25
#391 possibly related?

**Comment by marykerins** [comment] 2020-11-13 17:09
#391 is certainly in the same ballpark as this issue - errors are not being reported.  But the errors themselves seem to be different so I'm not clear if these 2 should be merged.  Depends I think on something like whether the fixes are similar and thus best done all at once.

**Comment by isc-bsaviano** [comment] 2021-05-07 13:07
@marykerins Can you download the latest beta version of this extension (found [here](https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.11-beta.14/vscode-objectscript-1.0.11-beta.14.vsix)) and try to reproduce this again? I recently merged a PR that fixes issue #391 and I think this issue is likely a duplicate of that one.

**Closed** 2021-11-02 17:57 UTC
Labels: bug
