### ISSUE TITLE
Multiple workspace can not use goto definition

### ISSUE THREAD

**Issue by a807875765** [intersystems-community/vscode-objectscript#779] opened 2021-11-24 02:31 UTC
Hello.I exoprt to multiple web server  but have same class  in one workspace but  i can not find goto definition 
![image](https://user-images.githubusercontent.com/58621768/143160427-f84b5322-80e3-45a6-9fc3-b793d1a69f3d.png)
if i use 
![image](https://user-images.githubusercontent.com/58621768/143160466-31b4e415-555e-46fa-b76d-bc0e4e70c9bb.png)
 is can not goto definition class or method 
I find I need to config objectscript.export  in setting.json but  no sample 
I just use default config 
![image](https://user-images.githubusercontent.com/58621768/143160790-fe2ce569-605e-4123-baa0-0ee2f35682fd.png)
but useless.what should I do ? thanks for your answer.

**Comment by a807875765** [comment] 2021-11-24 02:33
the setting.json path in project just like
![image](https://user-images.githubusercontent.com/58621768/143160967-2d4484ca-5160-48d8-8484-d644274f8a45.png)
![image](https://user-images.githubusercontent.com/58621768/143160995-d2315b34-dfee-4661-94a8-908d1df4e3af.png)

**Comment by isc-bsaviano** [comment] 2021-11-24 13:30
@a807875765 Is this a duplicate of #742?

**Comment by a807875765** [comment] 2021-11-24 14:57
It seems a little different。but i still  don't know how to configure,should i configure workspace.json
![image](https://user-images.githubusercontent.com/58621768/143260763-47ee4631-e645-4e69-99e5-6ea5b7b53d5c.png)
but in #742 seems like useless.I want know how could i configure export settings

**Comment by a807875765** [comment] 2021-11-24 15:23
in #742 can locate in one folder 
![image](https://user-images.githubusercontent.com/58621768/143264200-17e54b3a-67cf-4e02-bd06-00b56410b71e.png)
but  i want goto definition  for this path and this class  but i can not  find right mouse button options.and press F12 useless。
For example。I want  in path:D:// folder A  click  ##class(a) to find folderA a.cls file.and  in path:D:// folder B  click  ##class(a) to find folderB a.cls file but  now goto definition is useless .It's same question with #742 ? I'm a little poor at understanding. I'm sorry.this question can it be achieved through export setting. If possible, can you give an sample of  configure export setting? Thanks a lot！I'm  look forward to your reply.

**Comment by isc-bsaviano** [comment] 2021-11-24 15:56
@a807875765 I think this is a duplicate of #742. Here's an explanation of what you'd expect to see with the current behavior:
- If you have class A and class B in folder irisProject, pressing F12 on a reference to class B in class A will take you to your local copy of class B.
- If class A is in irisProject and class B is in irisProject1, pressing F12 on a reference to class B in class A will open a read-only server copy of class B.

Does this describe what you're seeing? Also, you should take a look at our documentation on [configuration](https://intersystems-community.github.io/vscode-objectscript/configuration/) and [server-side editing](https://intersystems-community.github.io/vscode-objectscript/serverside/), which you may want to adopt so you don't have to worry about exporting files to different local folders.

**Closed** 2021-11-25 00:30 UTC

**Comment by a807875765** [comment] 2021-11-25 00:32
yes.thanks for your answer
