### ISSUE TITLE
Breadcrumbs incorrect in multi-root ISFS workspace

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems-community/vscode-objectscript#1358] opened 2024-05-09 14:19 UTC
I do my development in a VS Code workspace with server-side editing and multiple workspace roots. There's a folder named "cls" filtered to classes, a folder named "rtn" filtered to routines, etc. Regardless of which folder I am in, the breadcrumbs at the top always say "rtn". If I click the "rtn" breadcrumb, it shows the other folders with the same name. I am on the latest beta version v2.12.4-beta.7
![image](https://github.com/intersystems-community/vscode-objectscript/assets/9560941/4ea94912-8667-45a4-bd47-024af85a5dc3)

**Comment by isc-bsaviano** [comment] 2024-05-09 14:25
@isc-pbarton Can you share the contents of your `.code-workspace` file please? Our extension doesn't have any control over breadcrumbs but if I find a way to reproduce this I can maybe file a VS Code bug report.

**Comment by isc-pbarton** [comment] 2024-05-09 14:31
@isc-bsaviano Here is my code workspace file:

```
{
	"folders": [
		{
			"name": "%SYS",
			"uri": "isfs://iscx-ccr-base/?ns=%SYS"
		},
		{
			"name": "cls",
			"uri": "isfs://iscx-ccr-base/?ns=CCR&filter=*.cls"
		},
		{
			"name": "rtn",
			"uri": "isfs://iscx-ccr-base/?ns=CCR&filter=*.inc, *.mac, *.int"
		},
		{
			"name": "CSP:/ccr",
			"uri": "isfs://iscx-ccr-base/ccr?csp&ns=CCR"
		},
	],
	"settings": {
		"objectscript.showExplorer": false,
		"objectscript.conn": {
			"active": false
		},
	}
}
```

**Comment by isc-bsaviano** [comment] 2024-05-09 15:43
@isc-pbarton This might be caused by the `?NS=...` query parameter. VS Code isn't that good at distinguishing between folders that have the same authority (the `iscx-ccr-base` piece). If you put the namespace in the authority, does that work? This is the more "modern" way to specify a namespace.

```json
{
	"folders": [
		{
			"name": "%SYS",
			"uri": "isfs://iscx-ccr-base:%SYS/"
		},
		{
			"name": "cls",
			"uri": "isfs://iscx-ccr-base:CCR/?filter=*.cls"
		},
		{
			"name": "rtn",
			"uri": "isfs://iscx-ccr-base:CCR/?filter=*.inc, *.mac, *.int"
		},
		{
			"name": "CSP:/ccr",
			"uri": "isfs://iscx-ccr-base:CCR/ccr?csp"
		},
	],
	"settings": {
		"objectscript.showExplorer": false,
		"objectscript.conn": {
			"active": false
		},
	}
}
```

**Comment by isc-pbarton** [comment] 2024-05-09 15:59
@isc-bsaviano Definitely looks related to not being able to distinguish between folders that have the same authority. If I put the namespace in the authority, now the %SYS folder has the breadcrumb correct, but the "cls" and "rtn" folders in the same namespace both show the "rtn" breadcrumb. That's still better than before, I'm happy to close if that's as good as we can get.

**Comment by isc-bsaviano** [comment] 2024-05-09 16:01
@isc-pbarton I'll report this as a VS Code core bug.

**Comment by isc-bsaviano** [comment] 2024-05-09 16:32
Closing in favor of linked VS Code issue

**Closed by isc-bsaviano** 2024-05-09 16:32 UTC
