### ISSUE TITLE
vscode extension host is crashing when $$$LogMessage is invoked at a high frequency ?

### ISSUE THREAD

**Issue by theanor** [intersystems-community/vscode-objectscript#751] opened 2021-10-15 08:55 UTC
The CompareFiles method in %UnitTest.TestProduction is using $$$LogMessage to display the names of compared files.
When running the test using vscode, the message is displayed in the debug console.

One of my test cases does a very rapid comparison of a lot (around 300) of files. When it is running using vscode, there are very frequent debug console updates. Most of the time (nearly each time in fact), the vscode extension host is crashing and the following gets displayed in the debug console : 

`[xmldom warning]	unclosed xml attribute
@#[line:undefined,col:undefined]`

The same test runs ok in Studio. If I override the method to suppress the $$$LogMessage, test is running ok in vscode.

Not sure what could be the cause. Looks like some form of concurrency issue, but not sure if it lies in the extension or in vscode itself.

I'm using vscode v1.61.1, InterSystems ObjectScript extension pack v1.0.3.

**Comment by isc-bsaviano** [comment] 2021-10-21 12:21
@theanor The global is `^CacheTemp.ISC.Atelier("debug")` on CE

**Comment by isc-bsaviano** [comment] 2021-11-03 15:23
Closing this issue because I couldn't reproduce it

**Closed by isc-bsaviano** 2021-11-03 15:23 UTC
Labels: debugger
