### ISSUE TITLE
CSP: Failed to save file '...' on the server

### ISSUE THREAD

**Issue by cvertee** [intersystems-community/vscode-objectscript#1345] opened 2024-04-10 06:03 UTC
For some reason i get 'Failed to save file *.csp on the server' error in VSCode. Sometimes it does work, sometimes it doesn't. Even if i try to edit the same file i can get lucky and successfully compile it. But this probability is heavily random and can't figure out why this happens from time to time. 
In the Output tab ObjectScript writes successful compiles or errors while compiling CLS files. But when such save error happens in CSP file there is just nothing. 

Language Server Output with verbose level only writes this when saving, no errors (uri contains path to file://)

```
Sending notification 'textDocument/didSave'.
Params: {
    "textDocument": {
        "uri": "..."
    }
}
```

IRIS Version: 2020.1
VSCode Version: 1.87.2
OS: Windows 10

**Comment by cvertee** [comment] 2024-04-10 06:07
Sometimes even after successful CSP compile, whenever i add something like alert(1)  and hit save it just starts giving errors. Super rarely can fix this by adding spaces after/before html tags

**Comment by isc-bsaviano** [comment] 2024-04-10 11:23
@cvertee The Language Server plays no role in the saving of documents so that log isn't going to help us. For local files, this extension determines the name of the CSP file by seeing if the file's path contains a web application name, and then saves the file on the server with the file's name begin the path starting at the web application folder name. For example, if you had file `src/csp/user/menu.csp` in your workspace and saved it, this extension would tell the server that the document name is `csp/user/menu.csp`. CSP saves can fail if this name is wrong. The best way to check the cause of the save failure is to get a network trace using a tool like Wireshark so we can see the REST request and response packets.

**Comment by cvertee** [comment] 2024-04-11 00:56
@isc-bsaviano thanks for the response! Not sure if i will be able to use Wireshark. Maybe will think of something for corporate computer stuff

**Comment by isc-bsaviano** [comment] 2024-04-11 11:49
@cvertee You can use the web gateway's HTTP Trace facility. It doesn't require you to download any other software. The UI and functionality is rudimentary but it will get the info we need to investigate this. See the [web gateway management pages docs](https://docs.intersystems.com/iris20241/csp/docbook/Doc.View.cls?KEY=GCGI_mgmtportal) and the [HTTP Trace docs](https://docs.intersystems.com/iris20241/csp/docbook/DocBook.UI.Page.cls?KEY=GCGI_monitor#GCGI_viewtrace).

**Comment by cvertee** [comment] 2024-04-12 03:34
@isc-bsaviano Will try to look on that (or something else) later when i'll find the time, thanks.

**Comment by isc-bsaviano** [comment] 2024-04-18 12:14
Hi @cvertee, just checking in to see if the trace revealed anything.

**Comment by cvertee** [comment] 2024-04-18 16:08
@isc-bsaviano Hi. Not working with IRIS for now. Tried to get to Web Gateway but probably nobody will let me get there (not the admin and whatever) so still thinking on possible workarounds

**Comment by isc-bsaviano** [comment] 2024-05-02 13:09
Closing this since I can't reproduce it. @cvertee please re-open if you find reliable reproduction steps.

**Closed by isc-bsaviano** 2024-05-02 13:09 UTC

**Comment by cvertee** [comment] 2024-11-19 07:05
Not sure if its somehow related. But whatever. I had csp file that just did not compile with vs code extension (same problem as described WITHOUT description)
But i found out something in source code related to base64 chunk sizes and tried to find problematic place in code (by deleting code and finding out which removed code make it work)
So i found something like
```js
window.onload = function() {
```

At probably exactly 12981 or 12982 character
```js
window.onload = function() {
// ----------^ here
```
when i move 
```js
 = function() {
```
at new line CSP file starts to compile

When i put it back, CSP again shows compile error, moving to new line and it works again, etc

Still can't say if its something problematic on the server or on extension side

**Comment by cvertee** [comment] 2024-11-19 07:07
@isc-bsaviano

**Comment by isc-bsaviano** [comment] 2024-11-19 12:07
@cvertee You are using client-side editing correct? csp files shouldn't be converted to base64 since they are text files. If they are, then that's a bug in this extension. Are you able to get a network trace like I mentioned above? If not, can you send me a test file I can use to reproduce this on my end?

**Comment by cvertee** [comment] 2024-11-19 13:02
@isc-bsaviano Yeah i edit file from the client (i guess) side, and can't send it here. About tracing kinda trying to think of something. Not even sure it'll help because if there is an error on server compiler it should return something to display in at least the output, no? 
Also maybe it'll be a good idea to add verbose log like in language server, so someone can easily see what happens/what json is returned during saving or other stuff, cause who knows maybe we'll see nothing in WebGateway or whatever.

**Comment by isc-bsaviano** [comment] 2024-11-19 13:26
@cvertee Compilation errors will appear in the Output window. Errors saving a file should as well, but if VS Code doesn't get a detailed error message back from the server then it won't Output anything. I will consider adding a setting that turns on logging for REST requests.

I tried to reproduce your issue again but couldn't. Without more info there's not much I can do. You can try opening an issue with the WRC. They will be able to screen share with you and their app is a secure way to share files.

**Comment by cvertee** [comment] 2024-11-19 15:41
@isc-bsaviano Thanks!

**Comment by cvertee** [comment] 2024-11-21 11:32
@isc-bsaviano finally sorted things out with WebGateway, i enabled HTTP tracing, saw that some csp sends /api/atelier/v3 PUT request with content NOT being base64 encrypted and this csp compiles succesfully without any troubles.
But when i do the same with the bad csp file (that doesn't give any error details) no PUT request is sent. No thing that looks like PUT /api/atelier, only some basic GET to /api/atelier for whatever reason (probably not related)

But when i go to the event log i can find something interesting, the name of the csp file that can't compile, part of the content and error
`Error Condition: Failed to read posted content from the client (Content-Length: 16229; Data Actually Read: 899; Read Error: 730054)`

**Comment by cvertee** [comment] 2024-11-21 11:37
What's more interesting is that i can edit file, remove some lines or whatever but it still gives the same 899 of Data Actualy Read, JSON in the event log is changing but for some reason cuts itself to 899 characters???

**Comment by isc-bsaviano** [comment] 2024-11-21 12:00
@cvertee Thanks for the information. Unfortunately, I'm not an expert on the web gateway or CSP. If you haven't already, I suggest you open a WRC case and give them a link to this issue and the $ZV of your server. It's probably pretty old since it only has Atelier API v3 (v4 was added in IRIS 2019.1 and Cache 2018.1.5?) so maybe this is a known CSP bug that's fixed in a later version. If you don't have WRC access then you can post this on the Developer Community (https://community.intersystems.com/) and someone there may be able to help.
