### ISSUE TITLE
csp-Files encoding issue

### ISSUE THREAD

**Issue by iscbernd** [intersystems-community/vscode-objectscript#692] opened 2021-06-18 11:53 UTC
I have a german customer complaining that csp-Files encoding gets changed on doing modifications in VSCode, then by IRIS-Studio 2020.1.x and so on and so on.

The issue is: Sometimes german umlaut's (ÄÖÜäöüß) gets broken/scrambled.

Please note: VSCode Files.Encoding general setting is set to utf8 (default)

For example you can start with a simple csp-file like this:

/csp/user/bmtest.csp

< HTML >
< head >
< title >ÄÖÜ< /title >
< /head >
< body >
< /body >
< /html >

then changing/adding < title > with german umlauts.

I start with the above in "UTF8 with BOM" (you can use notepad++ to check the encoding (or convert into other), please newly load the page to make sure proper display of content and encoding)

Here the steps I did:

- VSCode : display is ok, modifying title umlauts, then save and compile.
- Studio : display is ok.
- notepad++ : Loading csp-File, display is not ok, umlauts are scrambled up. The encoding has changed to Windows-1255 (why?)
Studio : modifying title umlauts, then save and compile.
- VSCode : display is ok. 
- notepad++ : Loading csp-File, display is ok, umlauts are correct, but encoding now has changed to ANSI (why?)
- VSCode : modifying title umlauts, then save and compile. -> Failed to import: The version of the file on the server is newer. What do you want to do? => "Overwrite on Server" (why? Nothing has changed!)
- Studio : display is ok, modifying title umlauts, then save and compile.
- VSCode : display is ok.
- notepad++ : Loading csp-File, display is ok, umlauts are correct, but encoding = ANSI.

I think we have a problem here.

Any ideas, etc.?

Many thanks and kind regards,
Bernd

**Comment by iscbernd** [comment] 2021-06-21 08:01
customer thought he found a workaround for this by conversion of csp-Files in "UTF8 with BOM" and in VSCode change settings as follows:

files.encoding="utf8bom"
files.encoding="windows1252"

PS: I am wondering about this since files.econding normally AFAIK does not support multiple encoding settings. Source of this workaround is unknown to me. Customer mentioned they found this hint/hack on stackoverlow.

Unfortunately, customer reports that this "workaround" did not work, since it now breaks working with class (cls) files.

Can someone please look into this? This is urgent for the customer.

Thank you,
Bernd

**Comment by daimor** [comment] 2021-06-21 08:40
From your points, I see no issues with VSCode or Studio, the only issues in Notepad++?
Notapad++ incorrectly detects the codepage, that's why this happening.
VSCode works with files every time the same way.
While Notepad++ has an option to autodetect encoding. So, I would suggest that's maybe wrong.

And I would suggest trying the newest version of Notepad++, which recently got a major update for a long time

**Comment by isc-bsaviano** [comment] 2021-06-21 14:05
@iscbernd I wasn't able to reproduce your error on my machine using server-side editing. Here's what I did:

1. In VS Code, opened a CSP file in my USER namespace
2. Added the line `<title>ÄÖÜ</title>`
3. Saved the file
4. Started Studio and opened the file
5. Line `<title>ÄÖÜ</title>` is present and formatted correctly

**Comment by iscbernd** [comment] 2021-06-21 16:16
@isc-bsaviano 
creating new csp file from VC code will create ANSI encoding file which works. Sometimes it creates UTF8 which later causes problems.

Try in VS code adding € (Euro-sign) and save and compile, seems to work. Try adding another umlauts and save and compile, Euro-sign changed in ? (question mark). Checking with np++ it is saying that encoding changed to windows-1255

If you create (for example in np++) a csp-file with german umlauts in uft8, despite VS Code file.encoding is utf8 by default, they are displayed incorrectly.

What seems to work for existing files is that if converted to "UTF8 with a BOM", it seems to work, also with € (Euro-sign).
(VS Code with file.encoding : "utf8")

Thx,
Bernd

**Comment by isc-bsaviano** [comment] 2021-06-21 16:57
@iscbernd I have a CSP file open server side with `UTF-8` and `<title>ÄÖÜ</title>` is displaying fine.

**Comment by isc-bsaviano** [comment] 2021-06-22 17:51
This has been raised internally, JIRA DP-406396

**Comment by isc-bsaviano** [comment] 2021-08-17 13:38
Closing because no changes need to be made to this extension related to this issue

**Closed by isc-bsaviano** 2021-08-17 13:38 UTC
Labels: upstream

**Comment by isc-tleavitt** [comment] 2025-03-31 18:53
Noting for future readers - the fix is a configuration change server-side:
Set ^%SYS("CSP","DefaultFileCharset")="UTF-8"
