### ISSUE TITLE
provide "export to filesystem" similar to "import from filesystem" for isfs folders

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#1164] opened 2023-06-05 06:59 UTC
From a ease of use side could we please include a short-cut to the export for UDL on isfs folders: e.g. "Export to local filesystem" which then prompts with a save dialog?

_Originally posted by @isc-lindensc in https://github.com/intersystems-community/vscode-objectscript/issues/1158#issuecomment-1572913579_

**Comment by isc-bsaviano** [comment] 2023-06-08 12:44
I don't think this is worth doing. VS Code's file picker for virtual workspaces, and it's save dialog, only support selecting a single document/file location. Exporting one at a time is likely not what most users are going to want. I think we should encourage the use for existing terminal APIs in the `%SYSTEM.OBJ.cls`, or in the SMP.

cc @gjsjohnmurray @isc-rsingh

**Comment by isc-bsaviano** [comment] 2023-06-15 16:36
I'm considering this a duplicate of #1158

**Closed by isc-bsaviano** 2023-06-15 16:36 UTC
Labels: duplicate
