### ISSUE TITLE
Search in Files inconsistent with Studio's Find in Files

### ISSUE THREAD

**Issue by LogMull** [intersystems-community/vscode-objectscript#1106] opened 2023-03-02 12:38 UTC
When using server-side editing with ISFS, I will often times get inconsistent search results compared to doing the 'Find in Files' search in Studio using the same search term over the same files.  Studio seems to always correctly find every instance while searching in VS Code will often times be lacking search results.  Usually this means that no results are found in VS Code, but occasionally it seems that partial results are returned.  VS Code does not always miss results, but it does so often enough that I usually resort to using Studio when I need to search the entire codebase for text.  

At least one time in the past, I observed the following when using VS Code's search:
Search for term, no results found
Open a file known to contain the term
Search again and the correct results are returned, including but not limited to the file just opened. (Not caused by the 'Search only in Open Editors' option. )

This happens in plugin versions as new as v2.4.2-beta.5 on VS Code version 1.74.2

**Comment by isc-bsaviano** [comment] 2023-03-02 12:44
@LogMull Can you reproduce this using `v2.6.1-beta.1`? There has been significant work in this area since `v2.4.2-beta.5` (see #1045 and #1102)

**Comment by LogMull** [comment] 2023-03-02 12:50
$zv gave me this result
Cache for Windows (x86-64) 2018.1.4 (Build 504U) Thu May 14 2020 14:20:15 EDT
I will give that version a try, did not realize I'd fallen that far behind.  Thanks for the info, excited to check it out!

**Comment by isc-bsaviano** [comment] 2023-03-02 13:01
@LogMull #1045 only applies to 2023.1+ but #1102 may fix your problem.

**Comment by isc-bsaviano** [comment] 2023-03-06 14:14
@LogMull Do you still see your problem using version `2.6.1-beta.1`?

**Comment by LogMull** [comment] 2023-03-08 16:28
Sorry for the late reply.  I have not noticed the issue after updating.  The problem was not always consistent, so I can't say for sure that it is fixed, but looking promising for sure.

**Comment by isc-bsaviano** [comment] 2023-03-08 16:45
Thanks for the reply @LogMull. I'm going to close this issue but feel free to re-open if you can reproduce the issue again reliably.

**Closed by isc-bsaviano** 2023-03-08 16:45 UTC
