### ISSUE TITLE
With 0.8.8-beta.13 fails to create new file

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#236] opened 2020-07-29 20:05 UTC
When creating a new class or new include, (server side) I get the following error

Unable to write file 'isfs://dev/HS/IHE/James.inc?ns=HSLIB' (EntryNotFound (FileSystemError): isfs://dev/HS/IHE/James.inc?ns=HSLIB)

I dropped back to beta.5 which I was running this morning and don't have the issue.

**Comment by gjsjohnmurray** [comment] 2020-07-29 23:00
@daimor this is caused by #221. The added call to _lookupAsFile [here](https://github.com/intersystems-community/vscode-objectscript/blob/801aeaf7626ce0d8115b0a6c47c6775b0c9fc94f/src/providers/FileSystemPovider/FileSystemProvider.ts#L113) throws an error when the file being written doesn't already exist on the server.

**Comment by gjsjohnmurray** [comment] 2020-07-31 16:40
@bourette if you have time please test with [beta.15](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.8-beta.15)

**Comment by gjsjohnmurray** [comment] 2020-08-03 12:06
@bourette 0.8.8 is now published. Please update and verify this issue is fixed.

**Comment by bourette** [comment] 2020-08-04 13:49
@gjsjohnmurray confirmed.

**Comment by gjsjohnmurray** [comment] 2020-08-04 14:56
@bourette thanks. Closing this.

**Closed by gjsjohnmurray** 2020-08-04 14:56 UTC
Labels: ?fixed, bug
