### ISSUE TITLE
Slow Import of Source

### ISSUE THREAD

**Issue by stefanc82** [intersystems-community/vscode-objectscript#1431] opened 2024-09-18 08:22 UTC
Type: <b>Bug</b>

Right clicking on my src folder in Explorer and selecting "Import without Compilation" is not working properly.
I have quite a large project and have done this many times before.
Currently it only loads the .inc files which takes about a minute. After another two minutes some of the classes are imported. Then it just stops or takes very long to response and only loads about 10 classes after every 5 minutes.

This happens on multiple devs' computers.

Output after running for about 10 minutes:

Extension version: 1.0.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13650HX (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (16.53GB free)|
|Process Argv|--crash-reporter-id e5f860dd-5001-45d4-ad2b-9c8cb79d3a64|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31125599
fje88620:31121564
iacca1:31138162
cc771715:31140165

```

</details>

**Comment by gjsjohnmurray** [comment] 2024-09-18 14:31
Probably a duplicate of #1428

**Closed by gjsjohnmurray** 2024-09-18 14:31 UTC
