### ISSUE TITLE
Debugger loses sync on larger volume output test suite

### ISSUE THREAD

**Issue by jpa95** [intersystems-community/vscode-objectscript#1170] opened 2023-06-20 14:28 UTC
When running unit tests that output large amount of text (think many tests and assertions in this class) the debugger loses sync (seems to hang) after a short while.
This was reproduced 10 out of 10 times. We do not have this problem on smaller test suites.

Studio v 2022.1.2 Build 574 runs this test suite correctly 100% of the time.

Note that when looking at the test run in the Management portal, the test suite run in VsCode is reported as being successful. So the tests are running but for some reason we are running out of buffer output space or something. 

Test Run #1
46710 bytes output / 352 lines / 279 Assertions / stuck after starting test #14

Test Run #2 (same test case order as Test Run #1)
46708 bytes output / 352 lines / 279 Assertions / stuck after starting test #14

Test Run #3 (different test case order)
49173 bytes output / 368 lines / 279 Assertions / stuck during test #14

Reproduced on : 
- InterSystems 2022.1.2.574.0
- VsCode 1.79.2
- InterSystems Language Server v2.3.5
- InterSystems ObjectScript v2.8.1
- Intersystems Server Manager v3.2.2

Best Regards!

**Comment by isc-bsaviano** [comment] 2023-06-20 14:43
Hi @jpa95, this looks like a duplicate of #751 but I will try to reproduce again.

**Comment by jpa95** [comment] 2023-06-20 16:11
Hi @isc-bsaviano, just tested your testcase in #751, and I always get the error message [xmldom warning] at file 166/167. Please see attached logs. Thanks!

[751 logs.zip](https://github.com/intersystems-community/vscode-objectscript/files/11803220/751.logs.zip)

**Comment by isc-bsaviano** [comment] 2023-06-23 13:44
@jpa95 I think I found the solution to this. I will include the fix in a PR with a handful of other debugger changes that I have queued up.

**Comment by GendronAC** [comment] 2023-06-23 13:53
Great job ! :) 

![image](https://github.com/intersystems-community/vscode-objectscript/assets/45271725/f1d477fe-a5e9-4616-90a2-feda5ea1a55e)

**Closed** 2023-06-27 11:40 UTC
Labels: bug, debugger

**Comment by jpa95** [comment] 2023-07-03 13:21
Thank you @isc-bsaviano !
