### ISSUE TITLE
Add Ability to Easily Override Inherited Class Members

### ISSUE THREAD

**Issue by isc-jsmith** [intersystems-community/vscode-objectscript#561] opened 2021-01-27 22:53 UTC
Issue Type: <b>Feature Request</b>

There appears to be no easy way to override inherited members on a subclass.  There should be a simple way of override methods (that aren't final), properties, or class parameters.

Extension version: 1.0.8
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:30:02.420Z)
OS version: Darwin x64 19.6.0

**Comment by isc-bsaviano** [comment] 2021-01-28 13:31
Closing this as a duplicate of https://github.com/intersystems/language-server/issues/71. The LS team is planning to add this feature in the future.

**Closed by isc-bsaviano** 2021-01-28 13:31 UTC
Labels: duplicate, language server
