### ISSUE TITLE
VS Code seems to color parens incorrectly

### ISSUE THREAD

**Issue by SCanzano** [intersystems-community/vscode-objectscript#1367] opened 2024-05-20 14:54 UTC
![image](https://github.com/intersystems-community/vscode-objectscript/assets/89160990/da4afa6a-38fa-4309-9e86-efe606bbc203)

I'm not an expert on the coloring in VS code but when I see red I think there is some form of an errors.  Maybe that's a misunderstanding on my part but I also don't understand why I see the close parent in Red but no open Paren in Red,

**Comment by isc-bsaviano** [comment] 2024-05-20 14:57
This is a duplicate of #1275 and https://github.com/intersystems/language-server/issues/253.

TLDR: the bracket pair colorization is handled by VS Code core and it's a known issue that it can't handle Embedded SQL. You can try opening an issue on the VS Code GitHub to see if they can adjust their code to support this.

**Closed by isc-bsaviano** 2024-05-20 14:57 UTC

**Comment by NHS-juju** [comment] 2025-05-13 12:51
Hey @isc-bsaviano - I was poking around this issue and wanted to run something by you as I hadn't seen this specific behaviour mentioned in the various instances of this issue being raised and closed, and wondered if this would change the current position of this being attributed to a fault with VSCode's bracket pair colourisation feature.

It seems that this issue only occurs when the curly bracket for the start of the method is on its own line (where it's placed on compile [^1] ).

For example:

![Image](https://github.com/user-attachments/assets/6e80ba47-7400-4eb5-8bbc-17f9a162007d)

- Method Test1() has the curly bracket on the same line as the method name etc, and the colourisation is as expected.
- Method Test2() has the curly bracket on a new line, and the colourisation is "broken".
- Method Test3() is the same as Test2 except for a leading  space, and the colourisation is as expected.

Does this point to a conflict between the syntaxes for [objectscript-class.tmLanguage.json](../../vscode-objectscript/tree/master/syntaxes/objectscript-class.tmLanguage.json) and [objectscript.tmLanguage.json](../../vscode-objectscript/tree/master/syntaxes/objectscript.tmLanguage.json) or a different type of fault with the extensions?

Additionally, if the above doesn't change things, are you aware of this being raised on the [VSCode Repo](https://github.com/microsoft/vscode/issues)? I certainly couldn't find anything logged there.

[^1]: In my screenshot, the curly brackets are in their various positions despite the class being saved/compiled, however closing and reopening the file does then have all 3 example methods with the curly brackets on their own line how as per how compiling formats methods. This varies slightly from how Studio would behave as the reformatting is presented immediately to the user on compile (presumably the opened class is refreshed on compile in Studio which is not happening in VSCode)

**Comment by isc-bsaviano** [comment] 2025-05-13 13:10
Thanks for the research @NHS-juju, it's very interesting. This bracket colorization is provided by VS Code.  I'm pretty sure it works independently from our language grammars or the semantic tokens provided by the Language Server extension. I just checked and I have never reported this issue to the VS Code team. If you report this there, definitely provide this research. The VS Code team is much more likely to respond to detailed issues.

**Comment by NHS-juju** [comment] 2025-05-13 13:46
Thanks @isc-bsaviano 

Just went to raise an issue with the VSCode team, and the first question in their template was _"Does this issue occur when all extensions are disabled?: Yes/No"_ so I thought I should try with all extensions disabled first as me answering no to this was a sure-fire way of the issue being closed off immediately.

Disabling _everything_ means I can't connect to my server to open the class, so I have disabled everything first, and then selectively enabled only the 3 extensions contained within the extension pack. In this configuration, the colourisation is as before.

However, when disabling the Language Server extension I get the following:

![Image](https://github.com/user-attachments/assets/ea1a216a-bbdf-4000-a795-51e40ef44094)

Working colourisation!

I'm unable to then try this with the Language Server enabled and the InterSystems ObjectScript extension disabled as attempting this will then disable the Language Server due to its dependencies:

![Image](https://github.com/user-attachments/assets/4fecd4c8-4621-4050-9d5f-75663808f384)

Unfortunately I'm very unfamiliar with how language servers are developed for VSCode (or any other IDEs for that matter) so would not be a good candidate for taking this further here or with the VSCode team, but I'm hopeful this is a small step in the right direction towards a resolution 🤞

**Comment by isc-bsaviano** [comment] 2025-05-13 13:59
Thanks for sharing all this info @NHS-juju! I can take it from here and open a VS Code issue. I will link it to this issue.

**Comment by NHS-juju** [comment] 2025-05-19 08:21
Hey @isc-bsaviano.

I have just tried this now, and I believe you have cracked it!

![Image](https://github.com/user-attachments/assets/7035fa83-64c7-4879-81d8-564bdacd51a1)
