### ISSUE TITLE
Issue with folders appearing empty in isfs

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#615] opened 2021-04-21 19:11 UTC
Reported by a member of my team (I've reproduced this issue):

Sometimes isfs directories appear as empty when a file from that directory is open. 

Steps to potentially reproduce the issue:
1.	Open a file in a directory (within an isfs folder)
2.	Open a file in another directory (within the same isfs folder)
3.	Click on the original file (without closing the directories)
4.	May need to click back and forth between the files

Symptoms of problem:
1.	Directory appears empty
2.	Clicking the refresh icon causes the files in the directory to flash temporarily then disappear again

Steps to make the files appear again:
1.	Click on a file not in the directory with disappearing files
2.	Click refresh
3.	(Note: clicking back on the file may result in the files disappearing again)

**Comment by gjsjohnmurray** [comment] 2021-04-27 22:09
Are the files classes and the directories packages? Or is this happening on an isfs root whose URL includes the `csp` queryparam?

Are you able to record an animated GIF or an MP4 video and paste it here?

**Comment by isc-tleavitt** [comment] 2021-05-03 14:52
@gjsjohnmurray the files are classes and the directories are packages. @isc-kiyer has observed the same behavior. I'll see about recording...

**Comment by isc-tleavitt** [comment] 2021-05-03 14:54
Note, I looked into this a bit and suspect (with corroboration from @isc-kiyer ) that this is a new issue stemming from changes to VSCode itself. I spent some time debugging in FileSystemProvider but was unable to identify the cause.

**Comment by isc-kiyer** [comment] 2021-05-03 15:04
Confirmed that the issue is present only in vs code v1.55+. I was unable to reproduce it with v1.54.3

**Comment by isc-tleavitt** [comment] 2021-05-03 15:08
Great, not too many things changed in that range... https://github.com/microsoft/vscode/compare/1.54.3...1.55.0

**Comment by gjsjohnmurray** [comment] 2021-05-07 08:38
Is this still reproducible with VS Code 1.56, which released a couple of days ago?

**Comment by isc-kiyer** [comment] 2021-05-07 13:27
Just checked and it is still reproducible

**Comment by isc-kiyer** [comment] 2021-05-09 18:42
@gjsjohnmurray I looked into this a little bit and it seems that with vs code 1.55+, the `stat()` method of `FileSystemProvider` gets called with "/" every time an open file gets clicked in addition to calling `stat()` with the file name.
I don't really understand why this causes the folder contents to disappear but I think this is a good starting point.
cc @isc-tleavitt

**Comment by Keshiyer** [comment] 2021-06-23 13:29
@gjsjohnmurray While trying to reproduce this issue for @isc-bsaviano, we noticed that the issue only arises when a filter is applied in the workspace. Any thoughts on why that would have such an affect/which files we should look at?

cc @isc-tleavitt

**Comment by isc-bsaviano** [comment] 2021-06-23 14:12
@gjsjohnmurray I was also able to reproduce this when opening an ISFS workspace that has an open file in a server:ns folder that has a filter in the URL. The file's contents load fine, but it doesn't get highlighted in the explorer tree and its package is empty when expanded. These issues don't occur if I repeat the same process, but with the open file in a server:ns folder without a filter in the URL.

**Comment by isc-bsaviano** [comment] 2021-07-07 18:15
@timleavitt @gjsjohnmurray I opened an issue in the VS Code repository for this bug. Feel free to add comments if I missed anything

**Comment by isc-bsaviano** [comment] 2021-08-16 12:50
A fix for this issue has been checked in to VS Code and is now available in the latest version of VS Code Insiders

**Closed by isc-bsaviano** 2021-08-16 12:50 UTC
Labels: bug, upstream

**Comment by isc-kiyer** [comment] 2021-08-16 12:57
Confirmed that the issue is resolved in the following insiders version:

Version: 1.60.0-insider
Commit: 9dd4f31a21d63deea5e1fc322cfc802413b31d95
Date: 2021-08-16T05:20:16.270Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.3.0
