### ISSUE TITLE
Unable to view read-only copy of routine in ObjectScript Explorer on Cache 2016.2.3

### ISSUE THREAD

**Issue by PaulSiml** [intersystems-community/vscode-objectscript#454] opened 2020-10-30 16:00 UTC
If a routine only exists in a namespace (not in the local Git repo), we can click on that routine in ObjectScript Explorer and successfully load a read-only copy for review on Cache 2017.2.  However, if we attempt the same operation on Cache 2016.2.3, we receive an error.  We receive the following message:  "Unable to open' [filename].mac': An unknown error occurred".  This is very easy to replicate.  Just create a routine in Studio on Cache 2016.2.3. Then click on that file in ObjectScript Explorer.  This has been verified by InterSystems Support - ObjectScript 1.0.1

**Comment by gjsjohnmurray** [comment] 2020-10-30 16:44
Unable to repro with v1.0.4 of the extension. Here are my steps:

1. Created a new local folder and opened it in VS Code.
2. Linked it to SAMPLES namespace on server with $zv="Cache for Windows (x86-64) 2016.2.3 (Build 903_6U) Mon May 7 2018 23:17:03 EDT"
3. In ObjectScript Explorer, expanded Routines folder and opened hello.mac successfully.

@PaulSiml are you able to repro the issue after updating extension to 1.0.4?

**Comment by PaulSiml** [comment] 2020-10-30 18:21
Hi John,

Ok … let’s talk about the password issue.  We are only using the ObjectScript Extension – nothing else.

Our connection setup works on 1.0.1  … what happened with 1.0.3 … it does not work?

I can simply switch out the extension versions, back and forth, in VS code with no changes to our Cache setups or settings.json file.

Version 1.0.1 works
Version 1.0.3 does not.

What can I say?  No Changes in our Cache configuration or Settings.Json files.

Our setup is simple:

 "objectscript.conn": {

      "active": true,
      "label": "mltestsrv1",
      "host": "mltestsrv1",
      "port": 57772,
      "username": "PXS",
      "password": "",
      "ns": "PXS",
      "https": false,
    },

So something does not seem correct on the extension.

For now, we have to stay on 1.0.1 or our developers are dead in the water.

-Paul

**Comment by gjsjohnmurray** [comment] 2020-11-02 12:07
@PaulSiml your 1.0.3 connection issue is being addressed in #458 and a fix for it is present in 1.0.5-beta.2

Once you have verified that fix, please re-test the issue you originally logged here. If it still exists in 1.0.5-beta.2 or later I will try again to reproduce it.

**Comment by PaulSiml** [comment] 2020-11-02 13:31
Good News

I have tested extension 1.0.5-beta2 on both Cache 2016.2.3 and 2017.2.2 and it now performs as expected … I am prompted for a password and the password is properly validated allowing me to connect again.  I only tested the connection capability and the ability to open and expand the ObjectScript Explorer tree.

I still cannot load a read-only copy of a routine that only exists in the namespace (not in local repo) in Cache 2016.2.3 – it throws an error.  It does work properly on Cache 2017.2.2

Thanks,

-Paul

**Comment by ConnieGaoISC** [comment] 2020-11-02 16:21
Hi @gjsjohnmurray @PaulSiml, I am Connie from WRC who original worked with Paul through WRC regarding this problem. I was able to reproduce this issue at my side as well. However, as I played around a bit more earlier today, I found the problem was gone after I created a new local folder and opened up in VS Code. This folder was identical to the previous one, same location, same privilege, both empty, and no hidden files. Now I can view the code from my Cache 2016.2.3 server with my new folder opened in VS Code, but can still reproduce the problem if I switch back to the old folder. The only difference I can think of is that the old folder is created while I was testing VS Code Object v0.9, before my Cache 2016 instance being setup, whereas the new folder was created today. I have no idea why this behavior could happen, but hopefully this piece of info can help.

**Comment by ConnieGaoISC** [comment] 2020-11-02 18:45
**Steps of how I reproduced the issue:**
1. I installed a Cache 2016.2.3 instance on Windows server 2012. 
2. In Studio, I created a demo class and compiled it under "User" namespace.
3. In VS Code, edited the  "intersystems.servers" json file to add this server, then changed "objectscript.conn" to connect to it.
4. Then in VS Code I opened up my existing file directory through File -> Open..., then switched to the ObjectScript Explorer and tried to open the class I just created, but then I failed with error "_Unable to open <class name>: An unknown error occurred. Please consult the log for more details.."_

I checked the VS Code log but only see error "An unknown error occurred" which might be relevant.

**Steps of how I fixed the issue:**
1. Under the same path where I created the previous file directory, I created another one. 
2. In VS Code, I went to File -> Open... and opened this new directory.
3. I went to the ObjectScript Explorer, double clicked the server side class, this time I was able to see the code without any problem.

**Comment by gjsjohnmurray** [comment] 2020-11-03 00:00
@ConnieGao-CG I haven't yet managed to repro this, but I did find a couple of paths that probably cause the message to state "An unknown error occurred".

Please download [this 1.0.5-dev.470](https://github.com/intersystems-community/vscode-objectscript/suites/1440484941/artifacts/24410939) vsix file and install it (e.g. by drag/drop onto the Extensions list). Then repro the problem. I'm hoping the error message will give more information this time.

**Comment by PaulSiml** [comment] 2020-11-03 12:36
Hi Connie,

I was able to create the folder in the file system, open that directory, and then use ObjectScript Explorer to load the file as a read-only copy.

I found this procedure confusing since we have to open a different directory and I suspect that eventually someone here would push this directory into our source control system.  However, it is another data point that should help ObjectScript developers track down the root of the problem should they choose to fix it.

Also we use the following:

objectscript.export.addCategory": true

So we would not want extra directories.


-Paul

**Comment by ConnieGao-CG** [comment] 2020-11-03 16:26
@gjsjohnmurray I just tested 1.0.5-dev.470 version. This time the error I saw is "Unable to open 'xxx.cls': Not Found."

**Comment by gjsjohnmurray** [comment] 2020-11-03 17:17
I can repro this if I create and save a class or mac using Studio, then refresh the ObjectScript Explorer (OE) so the new item is listed, then delete it from the namespace (e.g. using Studio or Portal to do this), then click on the item in OE.

What happens if you use the Atelier API directly from a web browser to try and get a class or mac that was producing the "Unable to open" message?

For instance:

http://localhost:57772/api/atelier/v1/USER/doc/YJMOS454.mac

or 

http://localhost:57772/api/atelier/v1/USER/doc/MyPackage.MyClass.cls

**Comment by ConnieGao-CG** [comment] 2020-11-03 17:43
I don't need to delete anything from the server side to repro this error, all the code is there existing on the server and I can view them once I open another file directory in VS Code. 

Per your request, I just tried two URLs to test:

http://172.17.208.46:57772/api/atelier/v1/USER/Test/DemoCls1.cls
http://172.17.208.46:57772/api/atelier/v1/USER/TestRtn1.mac

I didn't see any error and below is what I got from the browser:

{"status":{"errors":[],"summary":""},"console":[],"result":{}}

**Comment by PaulSiml** [comment] 2020-11-03 18:34
Hi Connie,

Can you tell me how the ObjectExplorer export option is supposed to work?

If the routine/class already exists in the local repo and you chose export of that routine/class in ObjectScript explorer, will that over-write the existing repo file and force a source control change?

-Paul

**Comment by gjsjohnmurray** [comment] 2020-11-03 21:33
> Per your request, I just tried two URLs to test:
> 
> http://172.17.208.46:57772/api/atelier/v1/USER/Test/DemoCls1.cls
> http://172.17.208.46:57772/api/atelier/v1/USER/TestRtn1.mac

@ConnieGao-CG you missed out the /doc/ part of the path, and also used / where the Atelier API needs . as package separator. Please try these:

http://172.17.208.46:57772/api/atelier/v1/USER/doc/Test.DemoCls1.cls
http://172.17.208.46:57772/api/atelier/v1/USER/doc/TestRtn1.mac

**Comment by ConnieGao-CG** [comment] 2020-11-03 21:49
Sorry about that. Below are the test results using correct URLs:

http://172.17.208.46:57772/api/atelier/v1/USER/doc/Test.DemoCls1.cls
{"status":{"errors":[],"summary":""},"console":[],"result":{"name":"Test.DemoCls1.cls","db":"USER","ts":"2020-10-29 12:24:18.962","upd":true,"cat":"CLS","status":"","enc":false,"flags":0,"content":["Class Test.DemoCls1 Extends %Persistent","{","","Property Name As %String;","","Storage Default","{","<Data name=\"DemoCls1DefaultData\">","<Value name=\"1\">","<Value>%%CLASSNAME</Value>","</Value>","<Value name=\"2\">","<Value>Name</Value>","</Value>","</Data>","<DataLocation>^Test.DemoCls1D</DataLocation>","<DefaultData>DemoCls1DefaultData</DefaultData>","<IdLocation>^Test.DemoCls1D</IdLocation>","<IndexLocation>^Test.DemoCls1I</IndexLocation>","<StreamLocation>^Test.DemoCls1S</StreamLocation>","<Type>%Library.CacheStorage</Type>","}","","}",""]}}

http://172.17.208.46:57772/api/atelier/v1/USER/doc/TestRtn1.mac
{"status":{"errors":[],"summary":""},"console":[],"result":{"name":"TestRtn1.mac","db":"USER","ts":"2020-11-03 12:31:12.138","upd":true,"cat":"RTN","status":"","enc":false,"flags":0,"content":["ROUTINE TestRtn1","TestRtn1","\t","\twrite \"Hello World!\""]}}

**Comment by gjsjohnmurray** [comment] 2020-11-03 21:59
Assuming your VS Code settings mean that it's connecting to that IP address, port and namespace, and with the same username as your browser used when accessing those two links, then I don't understand why the VS Code extension apparently gets a 404 response to the REST API call but the test from the browser the content of the class or routine.

**Comment by gjsjohnmurray** [comment] 2020-11-13 16:21
Please update to 1.0.6 (published today) and re-test. No guarantee it will have resolved your issue, but so far I haven't been able to reproduce it here.

**Comment by PaulSiml** [comment] 2020-11-16 12:53
Hi John,

It seems to have fixed the problem – 1.0.6
I will continue monitor the behavior.

Thanks, Paul

**Comment by gjsjohnmurray** [comment] 2020-11-16 14:06
Thanks Paul. Closing the issue.

**Closed** 2020-11-16 14:05 UTC
