### ISSUE TITLE
Multi-Server Support: Must Open .vscode/settings.json file in Workspace Subdirectory to Enable Opening of Class or Routine

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#247] opened 2020-08-03 14:44 UTC
I have a workspace set up with 4 directories, each directory having a .vscode/settings.json file that descirbes a Cache or IRIS server. I am using the Server Manager feature to supply the scheme, host and port information and my credentials are stored in the key-chain.

From the ObjectScript Explorer, I can expand the package and classnames for each server, but am unable to open or view any of them unless I first view or open the .vscode/settings.json file for that server/namespace in an editor.

I don't believe viewing/opening the settings.json file should be necessary, but if it is, it would be useful to understand why.

**Comment by gjsjohnmurray** [comment] 2020-08-04 09:03
So far I haven't been able to reproduce this. Here's my setup:

![image](https://user-images.githubusercontent.com/6726799/89274300-a1d7ab80-d638-11ea-8cda-823a57b74f43.png)

After taking that screenshot I closed all the document, exited VS Code, and reopened my workspace.

I had no problem opening a class from the OE view by clicking on it.

I also tested with my `intersystems.servers` definition in my user-level settings.json.

**Comment by gjsjohnmurray** [comment] 2020-08-04 09:06
Arose from #162

**Comment by DodgeDeBoulet** [comment] 2020-08-04 12:05
I have my servers defined at the User level. I tried your steps and still have the same issue, though. I'm going to move them to the workspace level and see if it changes anything.

I'm still getting the **Studio Action "Changed Namespace" not supported** messages in the Output panel, FYI.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 12:34
No change moving the servers to the Workspace level (and deleting them from the user level). Classes and routines refuse to open in an editor unless I have the settings.json file at the Directory level. And once I open **one** directory settings file, I can *sometimes* open classes and routines on other servers. But that seems quite random; I've been unable to discern a pattern yet.

One variable is that the connections I'm using are over a VPN and there's a bit more latency than with servers local to me. I don't know whether that factors into this issue at all.

**Comment by gjsjohnmurray** [comment] 2020-08-04 13:16
> I'm still getting the **Studio Action "Changed Namespace" not supported** messages in the Output panel, FYI.

This puzzles me. Are you positive you're using 0.8.8 of the extension? I've found that if I previously installed a beta or a snapshot then when the release is published I have to take steps to get it installed. Either uninstall what I have and install again from Marketplace, or opt to install a previous version from Marketplace (e.g. 0.8.7) and then trigger a check for extension updates.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 13:43
If this means anything, I am:
![image](https://user-images.githubusercontent.com/4532366/89299948-756e6000-d635-11ea-8d1d-e2cd4aa0e899.png)

I took the precaution of purging %USERPROFILE%/AppData/Roaming/Code and  %USERPROFILE%/.vscode, then installed the ObjectScript and Server Manager plugins. Unfortunately, the same result with regard to opening classes/routines ... and I'm still getting the "Changed Namespace" error as well.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 13:58
More datapoints:

I've removed the two Cache server directories from the workspace file. I can now open classes/routines on the first server in the list.

When I attempt to do the same thing on the 2nd server, I cannot open them on that server. However, if I select "add a namespace" with the + symbol, I can open classes in that namespace. And **after** opening classes in that namespace, I can go back to the still-shown original namespace on the 2nd server and open classes in it. But I cannot open classes on the 1st server any more!

Also, after removing the two Cache servers, I am no longer getting the "Changed Namespace" error in the Output panel.

**Comment by daimor** [comment] 2020-08-04 14:27
The key feature of settings when multi-root workspace used, that your objectscript.conn has to be defined on the lowest level, so, it should be only in `.vscode/settings.json`.
If you have `objectscript.conn` in `.code-workspace` file, or in user's settings, it will be merged on the lower level, and replaced with values lies below, but may still re-use values from levels above.

When you faced the issue when VSCode seems connected to the wrong place, you can try to force check connection, by action `Refresh connection` from the menu appeared by click in the status bar.

**Comment by gjsjohnmurray** [comment] 2020-08-04 14:47
That's useful information.

What is the $ZVERSION of the two Cache servers?

> When I attempt to do the same thing on the 2nd server, I cannot open them on that server. However, if I select "add a namespace" with the + symbol, I can open classes in that namespace. And **after** opening classes in that namespace, I can go back to the still-shown original namespace on the 2nd server and open classes in it. But I cannot open classes on the 1st server any more!

I have found the bug causing this and am about to submit a PR.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 14:50
$ZV = Cache for UNIX (SUSE Linux Enterprise Server for x86-64) 2018.1.2 (Build 309_5U) Wed Jun 12 2019 20:07:36 EDT

**Comment by gjsjohnmurray** [comment] 2020-08-04 15:05
@DodgeDeBoulet please verify the fix in https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.9-beta.2

**Comment by gjsjohnmurray** [comment] 2020-08-04 15:19
> Also, after removing the two Cache servers, I am no longer getting the "Changed Namespace" error in the Output panel.

@DodgeDeBoulet after installing 0.8.9-beta.2 please re-add those Cache servers. Do you still get the "Changed Namespace" messages? If so, are your Cache servers set up with a server-side source control class on any of their namespaces? Also, what is the $ZV of the IRIS servers, which don't produce that message?

**Comment by DodgeDeBoulet** [comment] 2020-08-04 15:21
It's definitely working better with the Cache servers, but now when I attempt to connect to the IRIS servers, I get:

![image](https://user-images.githubusercontent.com/4532366/89311844-8377ad00-d644-11ea-8641-c2f92ce11e85.png)

No errors in the OUTPUT panel, though. Only these popups.

**Comment by gjsjohnmurray** [comment] 2020-08-04 15:26
Please check the license usage information in Portal on those servers, in case you've somehow consumed all your licenses.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 15:31
> Please check the license usage information in Portal on those servers, in case you've somehow consumed all your licenses.

I currently show no licenses in use. Here's the descriptive data from the key:
```
Expiration date is 2/11/2050
Product=Server
License Type=Core Capacity
Server=Multi
Platform=X86-64(Red Hat Linux)
License Units=0
Licensed Cores=8
Authorized Cores=8
Extended Features=024F1C00
- Interoperability
- Analytics Run
- Analytics Analyzer
- Analytics Architect
- NLP
- Analytics VR Execute
- Sharding
- InterSystems IRIS
Production
```

**Comment by DodgeDeBoulet** [comment] 2020-08-04 15:34
Actually, that was the wrong server, but the correct one is essentially the same:
```
Product=Server
License Type=Core Capacity
Server=Multi
Platform=X86-64(Red Hat Linux)
License Units=0
Licensed Cores=8
Authorized Cores=8
Extended Features=024F1C00
- Interoperability
- Analytics Run
- Analytics Analyzer
- Analytics Architect
- NLP
- Analytics VR Execute
- Sharding
- InterSystems IRIS
Non-Production
```

**Comment by gjsjohnmurray** [comment] 2020-08-04 15:43
Are you still getting "Service Unavailable"? Does it help if you remove the two Cache workspace roots that you re-added? If not, does reverting to 0.8.8 fix it? Failing that, can the IRIS instances be restarted?

**Comment by DodgeDeBoulet** [comment] 2020-08-04 15:56
I've been able to get the Test IRIS server reconnected, and it appears I can switch between the two Cache servers and the one IRIS Test servers without issue.

I just this moment re-added the "Prod" server by changing its active state to true, and it prompted me for a password even though it was stored in the keychain. It did allow me to connect, though, and it remains active. I had tried that 4 or 5 times a few minutes ago and continually got failures. I know the password was correct because I copied and pasted when needed rather than typing it in.

The only difference between the two IRIS servers is that the "Prod" server is part of a mirror pair handled by a load balancer, but that shouldn't be any different than connecting via a Virtual IP.

**Comment by gjsjohnmurray** [comment] 2020-08-04 15:59
After changing "Prod" server's active state to true, please close the workspace and reopen it. Does it still fail to get that server's password from the keychain?

**Comment by DodgeDeBoulet** [comment] 2020-08-04 16:08
It's now failing to get the Test IRIS server's password from the keychain and is prompting for it to be entered. Entering the password manually is failing as well, and it does not proceed to open the Prod IRIS server. If I close and re-open the workspace, I get only the Cache servers in ObjectScript Explorer. If I attempt to set either of the IRIS servers to active = true, I get prompted for a password and authentication fails even though the password is correct.

Belay that ... looks like LDAP authentication has disabled my password again. Time to call the client's help desk ...

**Comment by DodgeDeBoulet** [comment] 2020-08-04 16:30
Ok. Password has been reset, and at the moment it appears as though I'm connected to all 4 servers. I've closed and opened the workspace and was still able to connect to all 4.

Not sure what happened on the AD/LDAP side; I logged out of my email session and back in again without issue but IRIS would not authenticate. I'm assuming there was some latency between domain controllers that allowed me to log onto email while my account was locked.

All good for now I guess. One question though: Should I be able to open more than one class at a time? In "normal" usage, a single click would view a file, and a single click on a different file would switch that tab to the other file. A double click would open the file for editing, and double-clicking on a different file would open that file in a new tab without closing the first file. That does not seem to happen with the ObjectScript plugin. Is that normal, or am I missing a setting somewhere?

**Comment by daimor** [comment] 2020-08-04 16:51
Desired behavior is, that you should be able to open any classes from any server, and when you switch between files, it should check where it supposed to be connected and show in the status bar correct server.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 17:19
> Desired behavior is, that you should be able to open any classes from any server, and when you switch between files, it should check where it supposed to be connected and show in the status bar correct server.

Thanks! Does the desired behavior include opening multiple classes from any server at the same time, in separate tabs?

**Comment by daimor** [comment] 2020-08-04 17:20
Yes, sure

**Comment by DodgeDeBoulet** [comment] 2020-08-04 17:22
Ok. I appear to have something misconfigured then. I can only open one class at a time.

**Comment by daimor** [comment] 2020-08-04 17:40
It looks like you are talking about another feature in VSCode itself, when you just open any file it may be replaced by the next opened one, when you try to edit it it will kind of fix it, then it will not be closed. Text on tabs for such just opened files is in italic, you can double-click the tab and it will fix it.

**Comment by DodgeDeBoulet** [comment] 2020-08-04 17:58
I was able to get multiple tabs by disabling **Workbench > Editor: Enable Preview**, while having **Workbench > Editor: Enable Preview From Quick Open** enabled. This appears to force all opened classes to be in Edit vs. Preview mode when single-clicking.

I cannot seem to get the single-click-to-preview, double-click-to-edit functionality I have for another environment (not Cache/IRIS; that one is C/C++), though. Both of the options in the previous paragraph are enabled there and it works as expected. However the ObjectScript plugin does not seem to be honoring them... can you reproduce this behavior?

**Comment by DodgeDeBoulet** [comment] 2020-08-05 02:52
I spent so much time figuring out how to open and view Classes in VS Code yesterday that I never got around to trying to edit them. Unfortunately, I get this error with everything I open when I try to edit:

![image](https://user-images.githubusercontent.com/4532366/89366134-43481700-d6a4-11ea-9911-8ef917ba8b07.png)

When I double-click the class name in the sidebar, it opens with the tab title in italics. That's "preview mode," which is read-only. Theoretically, double-clicking the tab title should allow me to edit it. The tab name does change from italics to a regular typeface, but the class remains opened read-only. I can find nothing in the VS Code that controls this behavior. And I do not have any source control enabled in IRIS.

I see the same behavior in Cache.

**Comment by daimor** [comment] 2020-08-05 05:52
It’s correct behavior, due to misunderstanding the purpose of server explorer. This is only for exploring server’s code.

And there are two ways next, 
- Preferable, export needed classes from explorer view, and you’ll be able to edit your local files, and they will be compiled when saved. In this case you can start to use source control
- use isfs, in this case you will edit them directly on server

**Comment by DodgeDeBoulet** [comment] 2020-08-05 11:50
Thank you, Dmitry,

I've switched to isfs:// with the following Workspace settings.json:

```
{
	"folders": [
		{
			"name": "cache-prod:QMC",
			"uri": "isfs://cache-prod/?ns=PRD",
		},
		{
			"name": "cache-test:TEST",
			"uri": "isfs://cache-test/?ns=TEST",
		},
		{
			"name": "iris-prod:PRD",
			"uri": "isfs://iris-prod/?ns=PRD",
		},
		{
			"name": "iris-test:TEST",
			"uri": "isfs://iris-test/?ns=TEST",
		}
	],
	"settings": {
		"intersystems.servers": {
		"iris-prod": {
				"webServer": {
					"scheme": "http",
					"host": "irisprdlb.ourawai.org",
					"port": 52773
				},
				"username": "jdrumm",
				"description": "Ourawai Production Primary IRIS for Health."
			},
			"iris-test": {
				"webServer": {
					"scheme": "http",
					"host": "irisapp04lp.ourawai.org",
					"port": 52773
				},
				"username": "jdrumm",
				"description": "Ourawai Test/Dev IRIS for Health."
			},
			"cache-prod": {
				"webServer": {
					"scheme": "http",
					"host": "elena.ourawai.org",
					"port": 57772
				},
				"username": "jeff",
				"description": "Ourawai Production Primary for Ensemble."
			},
			"cache-test": {
				"webServer": {
					"scheme": "http",
					"host": "ioke.ourawai.org",
					"port": 57773
				},
				"username": "jeff",
				"description": "Ourawai Test/Dev for Ensemble."
			}
		},
		"objectscript.conn": {

			"active": true
		},
		"objectscript.serverSideEditing": true
	}
}
```
The names of the servers and certain other elements have been changed for client confidentiality reasons.

When I open this workspace, all servers appear to connect. However I get the following in the Output panel:

```
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported
Studio Action "Changed Namespace" not supported
```

I can browse, open and edit classes from Explorer, and they compile with Ctrl-F7. There does not seem to be a direct method to save them, however. When I attempt to do so, I get:

![image](https://user-images.githubusercontent.com/4532366/89409028-61873480-d6ef-11ea-8793-a43b722fa286.png)

When I choose Overwrite, I get a pop-up error "Failed to save '<classname>': Unable to write file 'isfs://cache-prod/User/Util/Production.cls?ns=PRD' (Unavailable (FileSystemError): Cannot read property 'code' of undefined)" with the options Retry, Save As... and Discard. The tab continues to show the "unsaved" indicator. If I choose Save As, I can save it locally.

**Comment by gjsjohnmurray** [comment] 2020-08-05 11:59
@DodgeDeBoulet I'm investigating these issues right now

**Comment by gjsjohnmurray** [comment] 2020-08-05 18:47
PRs #252 and #253 should fix these. @daimor once you have approved and merged these please point @DodgeDeBoulet at the beta VSIX containing both of those so they can be verified.

**Comment by gjsjohnmurray** [comment] 2020-08-05 20:37
@DodgeDeBoulet please download and install the VSIX for [0.8.9-beta.4](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.8.9-beta.4), then re-test.

**Comment by gjsjohnmurray** [comment] 2020-08-05 20:50
> In "normal" usage, a single click would view a file, and a single click on a different file would switch that tab to the other file. A double click would open the file for editing, and double-clicking on a different file would open that file in a new tab without closing the first file. That does not seem to happen with the ObjectScript plugin. Is that normal, or am I missing a setting somewhere?

This is #254

**Comment by DodgeDeBoulet** [comment] 2020-08-05 23:12
So far everything is working perfectly. I'm so glad my ineptitude was able to help in uncovering and squashing some bugs 😁

I'm going to be re-writing some custom Ensemble hosts over the next few weeks so I'll be giving it a workout. Thanks for all your efforts on this project!

**Closed** 2020-08-14 10:10 UTC
Labels: bug
