### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by Patresko** [intersystems-community/vscode-objectscript#1347] opened 2024-04-15 08:38 UTC
Labels in outline are shown multiple times instead of 1x. 

Example

```
printToConsole(x)
 W !, x
 QUIT

```
```
start

DO printToConsole("A")
QUIT
```

In outline you will see printToConsole 2x or more depend how many times you will reuse label in your code.

**Comment by gjsjohnmurray** [comment] 2024-04-15 09:31
Please paste a complete code sample that demonstrates what you mean, plus a screenshot.

**Comment by Patresko** [comment] 2024-04-15 10:05
I already past sample which is clear in my opinion. Create any routine file, define any label, reuse one of the created label in another label and you have duplicated routines in OUTLINE. 

I guess that OUTLINE should point only to label definition and not also where label is used. 

![image](https://github.com/intersystems-community/vscode-objectscript/assets/23163555/d7f849a7-2fff-47d9-a6f3-d3dc91e6b7c1)

**Comment by gjsjohnmurray** [comment] 2024-04-15 10:25
Here's a screenshot of my test, based on what you wrote:

![image](https://github.com/intersystems-community/vscode-objectscript/assets/6726799/9d7abee4-2f01-41a1-b7d5-7bdb3d503403)

**Comment by Patresko** [comment] 2024-04-15 10:49
Weird...

Can I have this problem due the server-side editing?

**Comment by isc-bsaviano** [comment] 2024-04-15 11:17
@Patresko No, that won't affect this. I agree with John, unless we see a full screenshot showing your code and the bad outline, and get a copy of that code, we aren't going to be able to reproduce this. Are you using the Language Server extension as well?

**Comment by Patresko** [comment] 2024-04-15 11:29
Here is parts which made outline 3x. Not full routine code because I guess its not necessary

```
 /***************************************************************************************************************************************************************************************
 =====================================================================================| SAVE GROUP |=====================================================================================
 | 
 | SAVE NEW GROUP OR EDIT EXISTING ONE OR ASSIGN TREATMENT FOR PARENT GROUP
 |
 | CHANGELOG:
 |
 ***************************************************************************************************************************************************************************************/
saveGroup

 QUIT:'wGroup.validateAll()
 
 SET grp = $S( $DATA(%var("groupID")) :##class(production.article.stocktake).%OpenId(%var("groupID")),  $G(%var("myGroup"),"")'="" :##class(production.article.stocktake).%OpenId(%var("myGroup")), 
 			   						 1:##class(production.article.stocktake).%New()
 			 )

 SET:'$DATA(%var("groupID")) grp.createdBy = %user

 // GET ALL TRANSLATED NAMES
 KILL tab
 
 DO txtGroupName.getData(.tab)
 
 // CLEAR ALL PREVIOUS RECORDS
 DO grp.groupName.Clear()
 
 SET value = ""
 
 FOR
 {
	SET value = $ORDER(tab(value))
	QUIT:value=""
		
	DO grp.groupName.SetAt(tab(value), value)
 }

 // GET ALL LINKED WORKPIECES
 KILL tab
 
 DO gGroupArticles.getData(.tab)
 
 // CLEAR ALL PREVIOUS SAVED WORKPIECES
 DO grp.articles.Clear()
 
 SET value = ""
 
 FOR
 {
	SET value = $ORDER(tab(value))
	QUIT:value=""
		
	SET article = ##class(production.article).%OpenId(tab(value, 1))

	DO:$G(%var("movedWPC"))'=article.%Id() grp.articles.SetAt(article, value)
 }
 
 // GET ALL LINKED USERS
 KILL tab
 
 DO gGroupResponsibles.getData(.tab)
 
 // CLEAR ALL PREVIOUS SAVED USERS
 DO grp.responsibleUsers.Clear()
 
 SET value = ""
 
 FOR
 {
	 SET value = $ORDER(tab(value))
	 QUIT:value=""
	 
	 SET usr = ##class(wcs.user).%OpenId(tab(value,1))
	 
	 DO grp.responsibleUsers.SetAt(usr, value)
 }
 
 IF $DATA(%var("groupID"))
 {
	 SET grp.editedBy = %user,
	 	 grp.editDateUTC = $ZDT($ZTS, 3)
 }
  
 SET:$DATA(%var("myGroup"))&&(%var("myGroup")="") grp.isPrivateGroup = 1
 
 // SAVE, RELOAD DATA AND HIDE WINDOW
 DO %sys.error(grp.%Save())
 
 // UPDATE ALL SUBGROUPS
 IF ($DATA(%var("groupID")) || ($DATA(%var("myGroup"))) ) && (grp.getTotalSubGroups() > 0)
 {
	DO loadWorkpiecesForTreatment
	
	SET sql = "SELECT ID, operation FROM production_article.stocktake WHERE parentGroup = "_grp.%Id(),
		 rs = ##class(%SQL.Statement).%ExecDirect(,sql)

	WHILE rs.%Next()
	{
		KILL %var("operationArticle")
		
		SET composition = $LISTFROMSTRING(%var("list")),
			   subGroup = ##class(production.article.stocktake).%OpenId(rs.ID)
 
 		SET ptr = 0, 
      		  i = 0
 
 		KILL data
 		
 		DO subGroup.operationArticles.Clear()
 
 		WHILE $LISTNEXT(composition, ptr, ID)
 		{
 			SET article = ##class(production.article).%OpenId(ID)
 	
 			IF (article.hasTreatment(rs.operation)) && ($DATA(%var("operationArticle", ID)) '= 1)
 			{
	 			SET i = $INCREMENT(i)
	 			
	 			DO subGroup.operationArticles.SetAt(##class(production.article).%OpenId(ID), i)

	 			SET %var("operationArticle", ID) = 1
 			}
 		}
 		
 		SET subGroup.active = $S( i > 0 : 1, 1:0)
 		
 		DO %sys.error(subGroup.%Save())
	}
 }
 
 IF (grp.getTotalSubGroups() = 0) || ($DATA(%var("myGroup")))
 {
 	// AUTOMATICALLY CREATE SUB GROUPS FOR GROUP WHICH DOES NOT HAVE
 	
  	DO loadWorkpiecesForTreatment
  	  	  	
 	SET sql = "SELECT ID FROM production_article.operation ORDER BY ID ASC",
 		 rs = ##class(%SQL.Statement).%ExecDirect(,sql)
 		 
 	SET parID = grp.%Id()
 	
 	WHILE rs.%Next()
 	{
		DO activateSubGroup(parID, rs.ID, 0)	
 	}
 }
 
 DO gGroupsOverviewRefresh, gOverviewRefresh

 IF gUserFavoriteGroups.visible
 {
	KILL data 

	DO gUserFavoriteGroups.getData(.data)

	SET value = "",
		 grps = ""

	FOR
	{
		SET value = $ORDER(data(value))
		QUIT:value=""

		SET grps = grps_$LB(data(value, 1))
	}

	DO %pgm.setPref("usrFavGroups", $LISTTOSTRING(grps))
 }
 
 KILL var("myGroup")

 DO wGroup.hide()
 
 QUIT

 /**********************************************************************************************************************************************************************************************************************
 =======================================================================================================| DELETE WORKPIECE FROM GROUP |=================================================================================
 | 
 | IF USER CONFIRM THEN DELETE WORKPIECE FROM ASSIGNED GROUP
 |
 | CHANGELOG:
 |
 **********************************************************************************************************************************************************************************************************************/  
deleteWorkpieceFromGroup(x)

 IF (x = 1)
 {
 	SET grp = ##class(production.article.stocktake).%OpenId(%var("articleGrp")),
 		%var("groupID") = %var("articleGrp"),
 		%var("removedArticle", %var("articleID")) = ""
 	
 	DO loadGroupData(grp.%Id(), 0),
 	   saveGroup
 	
	DO gOverview.remove(%var("selectedRow"))
 }
 
 KILL %var("groupID"), %var("selectedRow"), %var("articleGrp"), %var("removedArticle")

 QUIT

 /**********************************************************************************************************************************************************************************************************************
 ====================================================================================================| MOVE WORKPIECE TO SELECTED GROUP |===============================================================================
 | 
 | MOVE WORKPIECE FROM ONE GROUP TO ANOTHER
 |
 | CHANGELOG:
 |
 **********************************************************************************************************************************************************************************************************************/  
moveToSelectedGroup

 QUIT:'wSelectMoveGroup.validateAll()

 DO wSelectMoveGroup.hide()
 
 SET workpieceID = gGroupArticles.selectedRow.column.GetAt(1).value,
 	 workpieceDV = gGroupArticles.selectedRow.column.GetAt(1).displayValue,
 	   destGroup = sSelectMoveGroup.value,
 			 row = gGroupArticles.selectedRow.row

 SET %var("movedWPC") = workpieceID

 DO gGroupArticlesDelete(gGroupArticles.selectedRow.row),
 	saveGroup
 
 KILL %var("movedWPC")

 DO loadGroupData(destGroup)

 KILL tab
 
 SET tab(1) = workpieceID,
 	 tab(1, "displayValue") = workpieceDV
 
 DO gGroupArticles.addRow(.tab)
 
 SET %var("groupID") = destGroup
 DO saveGroup
 
 QUIT

```

![image](https://github.com/intersystems-community/vscode-objectscript/assets/23163555/030afb6a-804c-409f-99b6-dbfbd3bf5982)

**Comment by isc-bsaviano** [comment] 2024-04-15 11:39
@Patresko Thank you for that. I believe this is a bug in the Language Server extension, which provides the Outline. The duplicate entries in the outline seem to be caused by labels that are the first language element on the line, but not in the first column due to them being in the arg list of a `Do` command. I will close this issue and open a new one in that extension's repository and get this fixed for you.

**Closed** 2024-04-15 11:46 UTC
