### ISSUE TITLE
Calculated fields do not show in debugger

### ISSUE THREAD

**Issue by jonlent** [intersystems-community/vscode-objectscript#969] opened 2022-08-08 13:35 UTC
### Isuue
When viewing an object variable that has calculated fields, like the X12Document below, the calculated fields show as what appears to be uninitialized memory content. If the value is evaluated in the debug window, it will show the correct content:

### Example
![image](https://user-images.githubusercontent.com/920117/183429998-10fe14e6-a595-4438-a10d-b440dd65fa20.png)
![image](https://user-images.githubusercontent.com/920117/183430906-bb13d66f-0b11-4167-b5d0-1d99a360a62c.png)

**Comment by isc-bsaviano** [comment] 2022-08-08 19:28
@jonlent This is caused by the code on the server that gets the object properties. The values for the calculated properties aren't being calculated but that isn't being shown to the user in a friendly way. I think this should be handled in the same manner as MultiDimensional properties, where the property name is still shown, but there is no value displayed:

![Screen Shot 2022-08-08 at 3 27 16 PM](https://user-images.githubusercontent.com/44776135/183498425-80eac515-5efa-4890-87f2-18027c1548f8.png)

I'm against calculating the values because there may be side effects (i.e. the SqlComputeCode updates a global). This is consistent with the way the ZWrite command handled calculated properties.

**Comment by isc-bsaviano** [comment] 2022-08-09 14:17
@jonlent This will be fixed in IRIS 2022.3

**Comment by isc-bsaviano** [comment] 2022-09-14 20:24
Closing since the fix for this is in a publicly available kit ([2022.2.0.334.0](https://community.intersystems.com/post/intersystems-iris-iris-health-healthshare-health-connect-20222-developer-preview-7-published))

**Closed by isc-bsaviano** 2022-09-14 20:24 UTC
Labels: bug, debugger, upstream
