### ISSUE TITLE
support importing and exporting XML?

### ISSUE THREAD

**Issue by gaoshan001** [intersystems-community/vscode-objectscript#576] opened 2021-03-03 05:39 UTC
Similar to studio function:
1. Export the selected package or class file to local in XML form
2. Import the local XML into the server

**Comment by daimor** [comment] 2021-03-03 05:44
Could you explain the reasons of having the code in XML format?

**Comment by gaoshan001** [comment] 2021-03-03 06:09
Export XML file for deployment to other servers. cls file can't do it.
@daimor

**Comment by daimor** [comment] 2021-03-03 06:13
Why do you think so?
Cls can be imported the same way as XML, if the target system not outdated, but for an outdated system such XML will not help anyway.
Deployment is quite custom for any project. And this part should be done another way.
You have to use CI/CD for deployment.

**Comment by isc-bsaviano** [comment] 2021-04-19 20:37
Duplicate of #34

**Closed by isc-bsaviano** 2021-04-19 20:37 UTC
Labels: duplicate

**Comment by pjsulin** [comment] 2022-07-05 16:48
While I agree in theory that using .cls files is a better idea than xml, I don't believe they are equivilant. The ability to import without overwriting tune table is not supported by class import but is with xml import. We have to use custom scripts for cleaning tune table information out of class files, otherwise diff'ing files does not really work because they will always have slightly different floating numbers in selectivity. If you cannot use diff to see what files have changed, I'm not sure how you are actaully effectively using git. Because this is not supported, tune tables must be run after every deployment, before testing can be done, which turns a 5 minute deployment and testing cycle into a 35 minute cycle.

**Comment by isc-bsaviano** [comment] 2022-07-06 12:29
@pjsulin Unfortunately there's nothing we can do about that. If users require XML for source control then they can use server-side source control to export as XML while still editing as UDL. Existing source control classes that do this will continue to work. Users can also export as XML using the management portal or terminal if they need to create a file for deployment.

**Comment by pjsulin** [comment] 2022-07-06 15:09
Fully agree, limitiation is with import for classes compared to xml, not the vscode extension. Comment strictly meant for documentation purposes.
