### ISSUE TITLE
"View Other" fails in class with method generator

### ISSUE THREAD

**Issue by isc-pbarton** [intersystems-community/vscode-objectscript#1114] opened 2023-03-09 17:00 UTC
I open an ObjectScript class with at least one generated method. If I put my cursor in the body of any method in the class and do the "View Other" command, I expect to jump to the INT code. Instead I get a message with "There are no other documents to open."

Here's an example class to replicate:
```
Class example.test
{

Method Test() [ CodeMode = objectgenerator ]
{
	do %code.WriteLine($char(9) _ "write ""hello world!""")
}

Method Test2()
{
	write "hello world!"
}

}
```
Doing "View Other" from inside of either method fails.

Extension version: v2.6.1-beta.5
IRIS version: IRIS for UNIX (Red Hat Enterprise Linux 7 for x86-64) 2022.1 (Build 209U) Tue May 31 2022 12:13:58 EDT

**Comment by isc-bsaviano** [comment] 2023-03-09 17:10
@isc-pbarton I can't reproduce this using your exact class. Outside the methods, I get an option to pick the INT to open (.1 or .G1). Inside the methods, the command jumps right to the correct line of the .1 INT routine. I am using a much newer kit though so I will try using your version.

**Comment by isc-bsaviano** [comment] 2023-03-09 17:19
I also cannot reproduce this using your IRIS version:

`IRIS for UNIX (Ubuntu Server LTS for ARM64 Containers) 2022.1 (Build 209U) Tue May 31 2022 12:14:00 EDT`

**Comment by isc-pbarton** [comment] 2023-03-09 17:25
If it makes a difference, I am using server-side editing with ISFS and InterSystems Server Manager. I can test some more this afternoon to see if I'm able to replicate with client-side editing.

**Comment by isc-bsaviano** [comment] 2023-03-09 17:30
I tested using ISFS. Are you use that class is compiled correctly? Maybe it's not up to date with the source. You can check that using using `Do ##class(%RoutineMgr).TS("example.test.cls",.compileTime,.UpToDate) Write UpToDate`

**Comment by isc-pbarton** [comment] 2023-03-09 20:42
Thanks for your patience on this. The method generator was a total red herring. Following are some steps to reproduce from scratch using a Docker image.

Clone and install the ObjectScript Docker template:
```
git clone https://github.com/intersystems-community/objectscript-docker-template.git
docker-compose build
docker-compose up -d
```

Open VS Code in the working directory. Open the file `src/dc/sample/ObjectScript.cls`. With cursor in the body of method `Test`, do the View Other action. I am taken to the INT code for the class.

Edit the method to add a method description:
```
/// this comment breaks view other
ClassMethod Test() As %Status
{
    set a=42 
    write "It works!",!
    return a
}
```
Save the file to compile the class. With cursor in the body of the method again, do the View Other action. I get "There are no other documents to open". If I remove the comment and recompile, it remains broken. But if I rename the method to `Test2`, it fixes itself.

At this point I'm pretty certain it's not a problem in the VS Code extension, more an issue with the debug map in IRIS. Let me know if you'd rather close this issue and I can take it to IRIS support instead.

**Comment by isc-bsaviano** [comment] 2023-03-09 20:57
@isc-pbarton I followed those exact steps and the "view other" still works correctly for me. If there's actually an issue here then it would be in the server-side code that maps the source file and location to the INT file and location. I'm going to close this issue and you can take this to the WRC if you can still reproduce it.

**Closed by isc-bsaviano** 2023-03-09 20:57 UTC
