### ISSUE TITLE
Output window does not display results of unit tests

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#1291] opened 2023-12-28 17:58 UTC
This has been happening for a long time now (for years now!), but I never followed up on it until today.

When the unit tests are run after a routine/class compile, we get the results in the Output window. BUT, the actual results don't display.

See attachments for what I get in VScode vs in Studio.
[vscode output.txt](https://github.com/intersystems-community/vscode-objectscript/files/13788492/vscode.output.txt)
[studio output.txt](https://github.com/intersystems-community/vscode-objectscript/files/13788493/studio.output.txt)

In the VScode output, note the big space between the begins... and the passed message. In between all those, we get the actual results, like

**Comment by isc-bsaviano** [comment] 2023-12-28 18:02
@RyszardWithAZ What's your `$ZV`? There's a known server-side bug that affects compilation output redirection. I'm not sure how the unit tests are run on compile, but since the results are just console output the cause may be this known bug.

**Comment by RyszardWithAZ** [comment] 2023-12-28 18:04
> @RyszardWithAZ What's your `$ZV`? There's a known server-side bug that affects compilation output redirection. I'm not sure how the unit tests are run on compile, but since the results are just console output the cause may be this known bug.

IRIS for UNIX (Red Hat Enterprise Linux 9 for x86-64) 2022.1.2 (Build 574_0_22637U) Thu Jul 27 2023 18:49:43 EDT

**Comment by isc-bsaviano** [comment] 2023-12-28 18:12
Yeah, that version has the bug unfortunately. This has been fixed in versions 2022.1.4+, 2023.1.2+, and 2023.3. Since you're on an adhoc I doubt you can upgrade easily, but I can give you the devkey for the fix to include in your next adhoc. You can try a community edition kit of one of those versions to test if the fix resolved your issue.

**Comment by RyszardWithAZ** [comment] 2023-12-28 18:20
Oh that's great, I'll let my internal folks know that there's a fix coming!

**Comment by isc-bsaviano** [comment] 2023-12-28 18:21
No problem, happy to help! The internal tracking number for the fix is DP-424221.

**Closed by isc-bsaviano** 2023-12-28 18:21 UTC
