### ISSUE TITLE
Glitches in code highlighting

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#603] opened 2021-04-05 20:08 UTC
<img width="593" alt="Screenshot 2021-04-05 at 23 07 40" src="https://user-images.githubusercontent.com/2781759/113621043-cd95b000-9663-11eb-8ef4-6f6b8344d3ca.png">

**Comment by isc-jamien** [comment] 2021-04-05 20:10
This is a bug with VSCode semantic token rendering. If you view the semantic tokens, they are all correct. Microsoft need to fix this.

**Comment by isc-bsaviano** [comment] 2021-04-05 20:37
Closing as duplicate of https://github.com/intersystems/language-server/issues/29

**Closed** 2021-04-06 12:42 UTC
Labels: duplicate, language server
