### ISSUE TITLE
Certain parentheses not matching inside embedded SQL

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1275] opened 2023-11-21 14:52 UTC
Note the red parentheses in both sections of embedded SQL. In both cases there are mismatched (mis-colored) parentheses.

<img width="645" alt="Screenshot 2023-11-21 at 9 41 20 AM" src="https://github.com/intersystems-community/vscode-objectscript/assets/12203701/28388b07-b148-4a0c-a958-3157ba72c2db">

**Comment by isc-bsaviano** [comment] 2023-11-27 12:37
@isc-solon This is a bug in VS Code core's bracket pair colorization feature. Please open an issue on the [VS Code GitHub repository](https://github.com/microsoft/vscode/issues) so they can consider addressing it.

*Duplicate of https://github.com/intersystems/language-server/issues/253*

**Closed by isc-bsaviano** 2023-11-27 12:37 UTC

**Comment by isc-solon** [comment] 2023-11-27 16:11
I **really tried** to see if this issue had been reported already. :-(
