### ISSUE TITLE
Potential Issue re: Centralized Authentication 

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#255] opened 2020-08-06 13:56 UTC
When opening a multi-server workspace, it appears all servers are authenticated against even if no editors are open or servers are "expanded."

A failed authentication does not halt the sign-on process for the remaining servers when it prompts for credentials, and I believe this may trigger a failed authentication attempt limit when using a centralized authentication facility such as LDAP/Active Directory.

A potential solution would be to defer authentication until the server is selected from Explorer.

**Comment by gjsjohnmurray** [comment] 2020-09-03 18:48
@DodgeDeBoulet please try the beta at https://github.com/intersystems-community/vscode-objectscript/releases/tag/v0.9.1-beta.5 which brings a recent improvement by @timleavitt that serializes and deduplicates credential prompting.

**Comment by gjsjohnmurray** [comment] 2020-09-05 03:45
> @DodgeDeBoulet please try the beta... 

This is now released (0.9.1)

**Comment by lindensc** [comment] 2020-10-07 00:43
Hi, 
latest still has massive prompting for multi server workspaces. Especially if the ISFS tree was expanded when vscode got closed.
I get prompted for password for each "expanding", even though password is stored in keychain. 
![image](https://user-images.githubusercontent.com/53921721/95274592-65693b80-0885-11eb-83c1-637d87d11d8e.png)

Could we also look to get password stored in keychain per username, not only per servercon/username?

**Comment by gjsjohnmurray** [comment] 2020-10-15 18:43
> latest still has massive prompting for multi server workspaces. Especially if the ISFS tree was expanded when vscode got closed.
> I get prompted for password for each "expanding", even though password is stored in keychain.

@lindensc does this still happen for you with the latest Marketplace versions of vscode-objectscript and servermanager?

**Comment by lindensc** [comment] 2020-10-16 04:04
> > latest still has massive prompting for multi server workspaces. Especially if the ISFS tree was expanded when vscode got closed.
> > I get prompted for password for each "expanding", even though password is stored in keychain.
> 
> @lindensc does this still happen for you with the latest Marketplace versions of vscode-objectscript and servermanager?

@gjsjohnmurray I have just updated to latest vscode 1.50.1 with latest plugins for servermanager and objectscript and it looks like the issue is gone.

**Comment by theflyingape** [comment] 2020-10-22 12:19
Kudos for "v1" kick-off.  Whereas everything was working 'good enough' before especially using the keychain, we have had many interested developers engaged in a pilot of this the past couple of months.  But now the same issue reported here has surfaced for us.

Yesterday, I cleared each stored keychain password and then uninstalled the preview extensions; then updated everything to latest releases for code and these extensions.  I introduced a single server back into my workspace config and stored my password on it.

All was looking fine in that initial setup session for v1, so I added another namespace and another server. This morning, I launch my workspace session and boom: I get the flooded authentication errors which in turn disables by AD account for 20-minutes by policy.  Ugh!!

**Observations:**

1. None of the isfs: entries were left expanded, so why does the extension insist on challenging every entry on startup?  Can it do authentication only when the user expands it?  I'm trying to imagine how long the startup will take should any developer configure their workspace to navigate 4 servers with 20+ namespaces on each.

2. I noticed the objectscript.conn config no longer has any effect?  That is, even if I set "active" to false (below), it ignores it?  But also, I took the entire objectscript.conn out and it still attempts to enumerate through the 3 entries, flooding serve-side with authentication errors.

Help!!  Thanks for digesting this.

**cconsole.log** (yesterday's good entries):
10/21/20-15:17:42:060 (1623718) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/21/20-15:17:42:070 (1620168) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/21/20-15:17:42:117 (1620167) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/21/20-15:17:42:130 (284674) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted

**cconsole.log** (today's bad entries):
10/22/20-07:39:19:063 (1620166) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.1.21
10/22/20-07:39:19:071 (1642773) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.40
10/22/20-07:39:19:085 (1620167) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.42
10/22/20-07:39:19:103 (1642771) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted...(repeated 1 times)
10/22/20-07:39:19:103 (1642771) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.4.117
10/22/20-07:39:19:132 (1921796) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:143 (1620168) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.1.21
10/22/20-07:39:19:232 (284669) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.248.2.56...(repeated 2 times)
10/22/20-07:39:19:245 (1623718) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.42
10/22/20-07:39:19:263 (284680) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.4.117
10/22/20-07:39:19:302 (284671) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted...(repeated 1 times)
10/22/20-07:39:19:302 (284671) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.1.21
10/22/20-07:39:19:402 (284677) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.40...(repeated 1 times)
10/22/20-07:39:19:402 (284677) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.248.2.56
10/22/20-07:39:19:403 (1642771) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:406 (284671) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.40
10/22/20-07:39:19:414 (284674) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.42
10/22/20-07:39:19:423 (1620166) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:426 (284669) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:430 (1921798) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.40
10/22/20-07:39:19:444 (1921799) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:456 (284671) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:482 (1642773) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:19:985 (1620167) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.1.21
_... 36 more lines of invalid credential hits ..._
10/22/20-07:39:20:061 (1620168) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:21:439 (1642771) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.85.1.21
10/22/20-07:39:21:845 (1620166) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/22/20-07:39:21:854 (1921797) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
```
{
	"folders": [
		{
			"path": "C:\\Users\\rhurst\\Desktop\\Workspace\\CCC"
		},
		{
			"name": "watson:%SYS",
			"uri": "isfs://watson/?ns=%SYS"
		},
		{
			"name": "watson:CCC",
			"uri": "isfs://watson/?ns=CCC"
		},
		{
			"name": "toby:CCC",
			"uri": "isfs://toby/?ns=CCC"
		}
	],
	"settings": {
		"editor.cursorBlinking": "blink",
		"editor.cursorStyle": "block",
		"editor.minimap.enabled": false,
		"editor.tabSize": 4,
		"editor.wordWrap": "on",
		"intersystems.servers": {
			"watson": {
				"webServer": {
					"scheme": "https",
					"host": "watson.bidmc.org",
					"port": 443
				},
				"description": "Development Caché® 2018",
				"username": "rhurst"
			},
			"toby": {
				"webServer": {
					"scheme": "https",
					"host": "toby.bidmc.harvard.edu",
					"port": 443
				},
				"description": "TEST Caché® 2017",
				"username": "rhurst"
			},
			"/default": "watson"
		},
		"objectscript.conn": {
			"active": **false**,
			"https": true,
			"host": "watson.bidmc.org",
			"port": 443,
			"server": "watson",
			"username": "rhurst",
			"ns": "CCC"
		},
		"objectscript.serverSideEditing": true,
		"objectscript.showExplorer": false,
		"objectscript.format": {
			"commandCase": null,
			"functionCase": null
		}
	}
}
```

**Comment by daimor** [comment] 2020-10-22 12:43
There are few notes about your config. `intersystems.servers` and `objectscript.conn` works separately, and while you can disable connection in `objectscript.conn` with `"active": false` you have not way to do it with `intersystems.servers` while it used as `isfs`, any isfs usage enables connection by default.

We already have three extensions, and at least two of them can call API, and I suppose you already installed InterSystems Language server extension. Could you disable it for a while to check auditing logs, if it keeps flooding there after that

**Comment by theflyingape** [comment] 2020-10-22 12:47
OK, after allowing my AD account time to reactivate, I removed all the isfs: entries above and the objectscript.conn from my workspace config.  VS Code status showed ObjectScript as disabled, but I clicked to toggle connection and it reported "missing host, port, and ns" -- good -- but it also wrote a new objectscript.conn with active = false.

I re-added my objectscript.conn config and left active = false. I clicked to Toggle connection, it failed to authorize off the keychain and prompted my for my server password.  On the server-side log:

10/22/20-08:23:00:708 (1620166) 0 ZAUTHENTICATE: %Service_CSP for rhurst ERROR #49: Unknown status code: 49 (Invalid credentials) on 10.25.70.40

I entered my AD password, and it connected:

10/22/20-08:24:01:621 (1620166) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted

I was able to Add a Namespace from the server to Edit Code and was able to expand the workspace "folder" to reveal/edit source.  I restarted the VS Code session and everything was still working.

I toggled disable connection which set **active** = false.  I restarted VS Code session, but it still connected (successfully) -- what?  And **active** still shows as false.  Clearly, there is an extension startup process that is 'hitting the server' and 'getting in' by re-using my cached CSP session, despite **active** = false.  And despite specifically toggling to disable connection, that action apparently does not do a CSP 'logout'.  All my subsequent VS Code restarts, I don't see the CSP service binding hitting our ZAUTHENTICATE with my username/password pair.

**Comment by theflyingape** [comment] 2020-10-22 13:02
> There are few notes about your config. `intersystems.servers` and `objectscript.conn` works separately, and while you can disable connection in `objectscript.conn` with `"active": false` you have not way to do it with `intersystems.servers` while it used as `isfs`, any isfs usage enables connection by default.
> 
> We already have three extensions, and at least two of them can call API, and I suppose you already installed InterSystems Language server extension. Could you disable it for a while to check auditing logs, if it keeps flooding there after that

Ah, I disabled Language Server in the workspace and restarted -- my session reverted to a dark theme (from ISC light) and I do see ObjectScript as disabled!  So, Language Server is mucking my account up?

Anyway, I clicked the isfs "watson:CCC" folder and it "cycled" with an error:
`command 'vscode-objectscript.serverActions' not found`

Ugh, no server-side entries.  I re-started VS Code again (with active still left on false) and it auto-connected and expanded the folder.  I see server-side all these 'good' hits:
10/22/20-08:54:41:263 (1642771) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted...(repeated 7 times)

Does this sum up what we found here:

1. Language Server is competing with isfs: in a manner not suitable for central authentication (like we use with AD).  What's the best expedient way to inform that software extension group, i.e., are you a part of that or should I go off and reference this issue as a new issue on that extension?

2. The active boolean -- on startup -- has no effect.  Is that desirable?

**Comment by gjsjohnmurray** [comment] 2020-10-22 13:25
@theflyingape the interaction with Language Server (LS) is probably caused by #416 which is being worked on with high priority. See also https://github.com/intersystems/language-server/issues/33 on the LS repo.

**Comment by daimor** [comment] 2020-10-22 15:35
> command 'vscode-objectscript.serverActions' not found

I found the issue, it happens when you press escape when prompt about language server extension appeared

**Comment by gjsjohnmurray** [comment] 2020-10-25 19:52
@theflyingape please install https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.4-beta.4/vscode-objectscript-1.0.4-beta.4.vsix and re-test.

**Comment by theflyingape** [comment] 2020-10-26 14:38
Installed, thank you, the cconsole.log shows **1** attempt to connect on every reload for the first isfs entry (watson and also identified as the /default).

The 2nd isfs entry (toby), it prompts me for my password, even though it's stored in the keychain.  Regardless whether I enter my password or hit ESCape, it reports an authorized connection on toby and I can list / edit its isfs folder contents:

10/26/20-10:21:20:287 (97682) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/26/20-10:21:21:050 (8067) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted
10/26/20-10:21:21:423 (8071) 0 ZAUTHENTICATE: %Service_CSP for rhurst granted

Just for giggles, I edited the isfs entries and moved **toby** to the top, leaving /default=watson:
```
		{
			"name": "toby:CCC",
			"uri": "isfs://toby/?ns=CCC"
		},
		{
			"name": "watson:CCC",
			"uri": "isfs://watson/?ns=CCC"
		},
		{
			"name": "watson:SBX",
			"uri": "isfs://watson/?ns=SBX"
		}
```
When I reload VS Code, it connects to toby and prompts me for watson!  Again, it doesn't matter if I enter my password or hit escape -- I can list / edit its isfs contents.

So it's **working** if only to annoy?  :) 

While I do not have %SYS listed as an isfs entry, I see in the ObjectScript status bar watson.bidmc.org:443[%SYS] -- is that correct?

I also left a source file opened for editing from each server/namespace.  Upon reload, I got the 1st source file from each server, but was prompted for the 2nd watson namespace -- I pressed escape and it did not load the source file.  I could list and double-click it and it opened.

**Comment by gjsjohnmurray** [comment] 2020-11-13 16:43
@theflyingape we just published 1.0.6 which includes at least one fix that might be relevant to this issue. Please update, re-test, and let us know.

**Comment by theflyingape** [comment] 2020-11-16 11:36
Only one small exception on startup after the extensions update followed by the RELOAD: I got prompted that my credentials did not have enough privileges for atelier api on one of the servers.  Press ESCape on the authorization prompt, and I was still able to open each isfs server/namespace folder.  Every VSCODE restart has not prompted me any for credentials -- well done you!

**Comment by gjsjohnmurray** [comment] 2020-11-16 16:32
@theflyingape I was able to repro the authorization prompt appearing when RELOAD is performed after an extension upgrade, as long as I had an isfs document open. Haven't been able to find what's causing it, and since it's not going to happen often I'm closing this.

**Closed by gjsjohnmurray** 2020-11-16 16:32 UTC
